### ISSUE TITLE
Add support for multiple cwd/asset paths

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/wmr#110]
Most client projects I've worked on in the past year had the following directory structure:

```txt
/my-project
  /public <-- cwd
    favicon.ico
    index.html <-- should reference /src/index.js
  /src
    /components
      foo.js
    index.js <-- main entry file
  package.json
```

_Afaik this is the default of CRA and other cli's too. Haven't checked next.js._

This structure breaks `wmr`'s current assumption that everything is inside the specified `cwd`, as the files are "scattered" across `/public` and `/src`.

Over at in the our devtools code-base I'm facing a similar scenario:

```txt
/preact-devtools
  /src
    index.ts <-- main devtools entry
  /tests
    /fixtures <-- cwd
      page1.js
      page2.js
      index.html <-- should load /src/index.ts
```

A solution to that could be to be able to specify multiple `cwd` paths that are valid to be served from. On resolution it would iterate all cwd's and check if the requested file is present.

**Comment by developit** [comment]
Another thought: we might be able to use aliases, `file:` dependencies or a Rollup plugin for this.

**Comment by piotr-cz** [comment]
Is there any workaround for this?

I'm using similar project structure to separate sources from assets. It's also recommended by [Svelte](https://github.com/sveltejs/template), [Vite](https://vitejs.dev/) and [Nollup](https://github.com/PepsRyuu/nollup/tree/master/examples/example-preact).

**Comment by developit** [comment]
@piotr-cz the workaround is to not use a public directory. Our `public` is very different from CRA's, it's effectively a `src/`. You can use a structure like this to achieve the exact setup described:

```
package.json
src/
    index.html
    index.js
    components/
        foo.js
```

**Comment by marvinhagemeister** [comment]
Closing, because this has landed a while back via the [aliases](https://wmr.dev/docs/configuration#aliasing-and-path-mappings) config setting.
