### ISSUE TITLE
Add `--cwd` + `--base` cli options

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/wmr#142]
Following our conversation from today from slack:

- `--base` -> web root, default is `/public`
- `--cwd` -> the root directory to work in, default is `process.cwd()`

Lots of current code uses `cwd` for everything. We need to revisit which places need `base` and which `cwd.

**Comment by developit** [comment]
Note: we've since added `--public`, which replaces `--base` as described here. Now the options are `--cwd` (effectively `cd foo && wmr`) and `--public` (overrides `./public` detection to set the "web-facing files root" dir).
