### ISSUE TITLE
Aliases work differently for source code and npm packages

### ISSUE THREAD

**Issue by developit** [preactjs/wmr#178]
I haven't had time to diagnose this yet, but it seems like aliases are applied to source code by transforming imports for those modules, whereas imports for those modules found in npm modules are left unmodified:

```js
// index.js:
import 'react';
// index.js: (output)
import '/@npm/preact/compat';
```
vs:
```js
// node_modules/foo/index.js:
import 'react';
// node_modules/foo/index.js: (output)
import '/@npm/react';  // resolves to a second copy of preact/compat with this URL
```

**Comment by jstans** [comment]
> 
> 
> This is possibly caused by the fact that we [include the aliases plugin](https://github.com/developit/wmr/blob/3dbdcef7751a13eb4f1bea497e52386fb38d2143/src/lib/npm-middleware.js#L134) when compiling npm modules, but we're not passing it `cwd`.

Ran in to this issue myself and you've conveniently hit the nail on the head already! Will raise a PR.
