### ISSUE TITLE
Reload/HMR not working w/11ty

### ISSUE THREAD

**Issue by Snugug** [preactjs/wmr#182]
## Expected
Changing the HTML or JS should cause either a HMR or a hard reload

## Actual
11ty moves the file over as expected, or compiles (as needed) but `wmr` doesn't pick up the changes. Doing a manual reload works as expected. I've also tested w/just WMR, no 11ty in the pipeline, and it doesn't appear to be working there, either.

## System
* MacOS 10.15.7
* Shell: zsh
* Node: 12.19.0
* WMR: 0.0.12

Here's a minimal test-case:

**.eleventy.js**
```js
module.exports = function (eleventy) {
  eleventy.addPassthroughCopy('js');

  return {
    dir: {
      input: 'views',
      output: 'public',
      includes: '../templates/includes',
      layouts: '../templates/layouts',
      data: '../data',
    },
    dataTemplateEngine: 'njk',
    markdownTemplateEngine: 'njk',
    htmlTemplateEngine: 'njk',
    templateEngineOverride: 'njk',
  };
};
```

**views/index.html**
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>WMR Test</title>
  <script type="module" src="/js/index.js"></script>
  <style>
    body {
      background: blue;
    }
  </style>
</head>
<body>
  <h1>Hello World</h1>
</body>
</html>
```

**js/index.js**
```js
console.log('Hello World');
```

**package.json**
```json
{
  "name": "wmr-11ty",
  "version": "1.0.0",
  "scripts": {
    "11ty:watch": "eleventy --watch",
    "wmr": "wmr",
    "start": "run-p 11ty:watch wmr"
  },
  "devDependencies": {
    "@11ty/eleventy": "^0.11.1",
    "npm-run-all": "^4.1.5",
    "wmr": "0.0.12"
  }
}
```

**Comment by Snugug** [comment]
Hey, sorry to comment on a closed thread, but now that 1.1 is released I tried this again, and it still isn't working. I'm even able to remove 11ty from the stack, just running WMR from the root of a project and editing an `index.html` or `style.css` (or even a root, as opposed to submodule, `main.js` included as a module in my HTML) simply isn't reloading the site. If I do a manual reload my changes are served correctly, but no automatic reloading or HMR. Is there anything else I can share that'll help y'all debug this? Here's the full HTML that I've got:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>WMR Test</title>
    <link rel="stylesheet" href="/style.css">
    <script type="module" src="/main.js"></script>
  </head>
  <body>
    <h1>Hello World</h1>
  </body>
</html>
```

**Comment by JoviDeCroock** [comment]
@Snugug let's split this up in several issues:

- HMR on an index.html file doesn't work, that's something we're aware of afaik
- Root components HMR doesn't work, the current version of Prefresh used watches exported components, we'll need both the code transpiler and #262 for that to work
- I think HMR currently only works for css-modules, we'll need to add a case for full stylesheets.

So we'll need a feature for a change in `index.html` triggering a `location.reload()`, a non css-module triggering a `location.reload()` and the transpiler/hmr-bubbling to get resolved.

Does this sound right to you?

**Comment by Snugug** [comment]
@JoviDeCroock I'm not sure what the delta is between what you've tried and what I've tried. It's that HTML file in a `public` directory with empty `style.css` and `main.js` files, also in the `public` directory, with WMR 1.1 running from root (one level up) on Node 12.20.0 installed via Volta on MacOS 10.15.7 using ZSH. I've got the same results on two different computers with the same setup. I don't know if it'll help you debug, but trying out the WMR demo as described in the README works for me as expected (CSS and HTML reload on change) _until_ I remove the `<script type="module" src="/index.tsx"></script>` line; then it all stops reloading for me.

Happy to split this up into multiple issues; I think my only tweak would be CSS shouldn't trigger a `location.reload()` but rather should HMR like how BrowserSync handles CSS; being able to update styling while deep in state of a UX flow IMO is an important bit of functionality.

Would you like me to file these issues?

**Comment by JoviDeCroock** [comment]
#293 will handle the issue of hot-reloading full css-stylesheets, it takes the browser stylesheets and looks for one with a matching url and then replaces it.

So I guess the only issue is that reloading doesn't work without a `JS` entry, this is to be expected _currently_ because of how we decide to send down wmr.js, we can only inject an import for `wmr.js` when a js file gets imported. We could however opt to always inject this runtime into a `script type="module"`. I think this is worth an issue

**Comment by Snugug** [comment]
Sgtm. I'll add an issue
