### ISSUE TITLE
Move preact-iso package into WMR?

### ISSUE THREAD

**Issue by developit** [preactjs/wmr#190]
Following on from #174, the [preact-iso](https://npm.im/preact-iso) package isn't WMR-specific but we currently use it in scaffolded WMR projects. Should it be in the `packages/` directory in this repo?

**Comment by EmilTholin** [comment]
Either that or a separate repository would be great!

It's currently difficult to send documentation PRs to `preact-iso` as it's only a Gist at the moment, and it would be great with an issue tracker where potential functionality discussions could be had.

**Comment by JoviDeCroock** [comment]
This is as of #217 part of our packages folder.
