### ISSUE TITLE
Error on starting server

### ISSUE THREAD

**Issue by intrnl** [preactjs/wmr#202]
This seems to only happen on dev and serve, builds (with prerender) are unaffected.

```
$ DEBUG=1 npm run start

> start
> wmr

TypeError: Cannot read property 'address' of null
    at c7e (/home/intrnl/Documents/projects/public/first-wmr-project/node_modules/wmr/wmr.cjs:2:2713816)
    at u7e (/home/intrnl/Documents/projects/public/first-wmr-project/node_modules/wmr/wmr.cjs:2:2714675)
npm ERR! code 1
npm ERR! path /home/intrnl/Documents/projects/public/first-wmr-project
npm ERR! command failed
npm ERR! command sh -c wmr
```

Checked it and it seems to fail around [here](https://github.com/preactjs/wmr/blob/0b368e7/src/lib/net-utils.js#L49)

- node 15.3.0
- npm 7.0.15
- OpenSUSE Tumbleweed 20201130-0 (5.9.11-1-default)

**Comment by developit** [comment]
Funky - I'm thinking this might be an IPv6 issue. Can you try running with `DEBUG=1 HOST=localhost npm run start`?

**Comment by intrnl** [comment]
Seems to produce the same result

**Comment by developit** [comment]
Interesting. The error happens here:
https://github.com/preactjs/wmr/blob/556269b6a9d7ab083874bf0e0e88e2a5291c067e/src/lib/net-utils.js#L49

If you're up for it, you can run WMR from source:

```sh
cd /home/intrnl/Documents/projects
git clone git@github.com:preactjs/wmr.git
cd wmr && npm i

cd /home/intrnl/Documents/projects/public/first-wmr-project
DEBUG=1 node --experimental-modules ../../wmr/src/cli.js
```

I need to look into why the address is null.

**Comment by intrnl** [comment]
Ahh, this might be why.

https://nodejs.org/api/net.html#net_server_address
> server.address() returns null before the 'listening' event has been emitted or after calling server.close().

**Comment by intrnl** [comment]
I've got through, but then it seems that I've hit another road block, `HOST` environment variable was set to my machine's hostname by default.

**Comment by developit** [comment]
Interesting about HOST being defined by default. I'm not sure what we can do about that... is it something that would be common on a bunch of linux distros?

**Comment by intrnl** [comment]
I'm not sure about it being common, though I believe openSUSE might have had very early.

**Comment by joaopaulobdac** [comment]
I just got this error using

```console
$ wmr --host 0.0.0.0 --port 3000 --public 'src'
Cannot read property 'address' of null
```

I'm on wmr 1.0.0, node v15.4.0 and Arch Linux Kernel 5.9.14-arch1-1

**Comment by rschristian** [comment]
@joaopaulobdac The fix hasn't been released yet.
