### ISSUE TITLE
Direct `unpkg.com` imports

### ISSUE THREAD

**Issue by lukeed** [preactjs/wmr#211]
**Example**

You can add this to `pages/home/index.js` inside the demo, and then `console.log({ clsx })` anywhere inside the component.

```js
import clsx from 'https://unpkg.com/clsx?module';
```

When _developing_ with external HTTPS references, everything works fine – browser makes the runtime resolution just fine.

However, when doing a `build`, things get funky:

**Error Output** 

> after writing to disk, so must be prerender?

```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. Received protocol 'https:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:782:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36)
```

And the output itself it also incorrect – sample:

```js
// dist/chunks/class-fields.[hash].js
import{d as t,m as e}from"../index.f2ef73c1.js";import"https://unpkg.com/clsx?module";//...

// dist/chunks/index.0b0fb6d6.js
// NOTE: did not use "clsx" in this page – also trailing `null;`
import{s,m as t}from"../index.f2ef73c1.js";import"https://unpkg.com/clsx?module";null;const e="about_migxty";
```

The unpkg link gets added to every output chunk, despite only being used on one page. It _is_ correctly placed in `dist/index.[hash].js` – just should not be appearing everywhere else.

---

**Expected Behavior**

Should have been able to work with the `https://unpkg.com` link as is

**Ideal / Future Behavior**

Should inline `https://unpkg.com` links at `build` time, and treat them as `external` files (same as normal `npm` resolutions).

**Comment by lukeed** [comment]
Can confirm that `yarn demo:prod --no-prerender` removes the error, but the output chunks are still wrong/unexpected.

**Comment by lukeed** [comment]
Oh, and the same download-direct-links behavior should probably be applied to skypack too.

**Comment by lukeed** [comment]
The dangling `null;` is a remnant of the `style()` helper getting dropped/replaced

**Comment by developit** [comment]
I think we could turn on the original unpkg plugin to address this, at least for the case of unpkg and skypack.
