### ISSUE TITLE
Old and new components in DOM on url change with preact-iso Router

### ISSUE THREAD

**Issue by EmilTholin** [preactjs/wmr#221]
There is a very brief flicker in the DOM on url change because of both the old and new route children being rendered at the same time when using the `preact-iso` Router. Here it is magnified with a breakpoint:
![old_route_component_in_dom](https://user-images.githubusercontent.com/11573167/101089685-cc6d4d00-35b5-11eb-9fbb-ca2959fbbc5c.gif)

Is there any way of not having the previous children of the Router being rendered? I don't fully understand the code, but I assume it is this way for the awesome support of lazy components.

**Comment by developit** [comment]
Hiya! Yes - this is something I caught before the release but didn't have time to fix. It's relatively straightforward and I'll try to get it addressed ASAP.
