### ISSUE TITLE
Service Worker support?

### ISSUE THREAD

**Issue by Snugug** [preactjs/wmr#226]
A real common pattern with Service Workers, and the current [best practice for Workbox](https://developers.google.com/web/tools/workbox/guides/get-started ), is to write them as ESM for maintenance, butt since SWs don't support ESM, to compile them to an IIFE. Workbox's ptecache injection I can probably get working using the Rollup plugin support, but don't know how to get just that file, which isn't part of the ESM import graph, to compile.

Thanks!

**Comment by developit** [comment]
Hi @Snugug! If you're good with SW only being generated in production builds then the rollup approach should work out-of-the-box:

`npm i @web/rollup-plugin-workbox`

```js
// wmr.config.js

import { generateSW } from '@web/rollup-plugin-workbox';

export function build(options) {
  options.plugins.push(
    generateSW({
      swDest: '/build/sw.js',
      globDirectory: 'build/'
    })
  );
}
```

I think right now that plugin will unfortunately install its own copy of Rollup, as part of a workaround to generate IIFE regardless of the configured Rollup module type. I think it might be worth building a generalized version of the plugin:

```js
// plugins/workbox.js

/** @param {import('wmr').Options} options */
export default function workboxPlugin(options, { fileName, filter } = {}) {
  const publicPath = options.publicPath || '/';
  options.plugins.push({
    name: 'workbox',
    buildStart() {
      this.emitFile({
        type: 'chunk',
        id: '\0sw',
        fileName: fileName || 'sw.js'
      });
    },
    resolve(id, importer) {
      return id === '\0sw' ? id : null;
    },
    load(id) {
      if (id !== '\0sw') return;
      const code = `
      import { registerRoute } from 'workbox-routing';
      import { precacheAndRoute } from 'workbox-precaching';
      import { NetworkFirst } from 'workbox-strategies';
      registerRoute(e => e.event.request.mode === 'navigate', new NetworkFirst());
      precacheAndRoute(SW_ASSETS);
      `;
      return { code, moduleSideEffects: 'no-treeshake' };
    },
    generateBundle(_, bundle) {
      const assets = Object.keys(bundle).filter(filter || Boolean).map(f => (publicPath + f).replace(/\/index\.html$/, '/'));
      for (let f in bundle) {
        if (bundle[f].type === 'chunk' && bundle[f].facadeModuleId === '\0sw') {
          bundle[f].code = bundle[f].code.replace(/SW_ASSETS/, JSON.stringify(assets));
          break;
        }
      }
    }
  });
}
```

**Comment by Snugug** [comment]
So I'm looking at this on the 1.0.0 branch and this doesn't appear to be working, but it's unclear to me if it's not working because `wmr.config.js` doesn't appear to be picked up or if the plugin isn't working. Either way, from a Workbox perspective, supporting precaching ([precache list explanation](https://developers.google.com/web/tools/workbox/modules/workbox-precaching#explanation_of_the_precache_list)) is important, as is interoperability with the existing [precache injection settings](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.getManifest) as you rarely want to precache every single file of your webapp. The [workbox-inject](https://www.npmjs.com/package/rollup-plugin-workbox-inject) rollup plugin is setup to do this and drop in to a rollup build like any other plugin allowing you to write your service worker by hand, as opposed to the webpack one which generates a SW through config (we currently recommend the former, not the latter).

**Comment by developit** [comment]
Alrighty I finally had a few minutes to implement a complete Service Worker plugin for WMR. It's not published to npm, but provided as a plugin + recipe here:
https://github.com/preactjs/wmr/wiki/Configuration-Recipes#service-worker
