### ISSUE TITLE
Doc question: Multiple HTMLs? 

### ISSUE THREAD

**Issue by groundhogs** [preactjs/wmr#227]
How would one go about using this with multiple HTMLs? I like the idea of replaing `parcel` with `wmr` for my day to day mockups, but I'm fairly confused about this specific point.

Imagine I have this setup: 
```
public
> index.html
> user
> > account.html
> > change-password.html
> entries
> > index.html
> > edit.html
```

How do I make `wmr` work its magic with *all* the above files?

**Comment by developit** [comment]
Hi there - WMR should just pick them up. It looks for all HTML files when building for production, and during development there's nothing that has to scan for these - just loading the HTML in a browser should work.

**Comment by groundhogs** [comment]
Apologies for that! The impression I got from the docs was that it would work for a single HTML, so I thought this looked like a good thing to clarify. 
Thank you!

**Comment by developit** [comment]
Ah! That's a good point, the docs don't make that clear enough at all. Glad it wasn't a technical thing you ran into.

**Comment by developit** [comment]
I tweaked the readme - we'll get proper full documentation soon, for now I hope it's at least a little clearer.
