### ISSUE TITLE
Show a helpful error when attempting to import Node core modules

### ISSUE THREAD

**Issue by dbetteridge** [preactjs/wmr#229]
Repro steps
1) Create fresh WMR setup
2) `npm install uuid` (this uses the native 'crypto' api)
3) run `npm start`
4) 
`Error bundling crypto:  Error: Could not loadnpm/crypto@1.0.1/index.js: Package crypto does not contain file index.js`
`500 /@npm/crypto  - Could not loadnpm/crypto@1.0.1/index.js: Package crypto does not contain file index.js`

The package 'crypto' on npm is deprecated, so it is visibly failing. Not sure if this is potentially happening elsewhere where sub-dependencies on javascript built-ins are being re-routed to npm

**Comment by developit** [comment]
WMR doesn't polyfill node built-in modules. Would it be possible to use Web Crypto or import `crypto-browserify`?

**Comment by dbetteridge** [comment]
Ahh, I'm being a dolt!

Ill swap to a clientside friendly library, so I understand properly 'crypto' is a node API and doesn't exist in browser so wmr is going to npm for it?

**Comment by rschristian** [comment]
> I'm not super deep on Crypto, but the idea behind WMR not handling this out of the box is to prompt folks to double-check whether browser variants of Node core modules are actually the right tool for the job.

I haven't looked into the module resolution stuff too deeply yet, but I'm wondering if it might be possible/useful to produce some sort of warning message when this occurs? It would require a bit of maintenance to keep the list of core modules up to date, but might be more clear for the end user. Especially with some packages that don't document they rely on Node core stuff.

**Comment by developit** [comment]
@dbetteridge yup, that's exactly what was happening.

@rschristian that's an excellent idea. We could even have the error message link to somewhere that lists recommended browser alternatives to Node core modules.

**Comment by developit** [comment]
I've re-opened this issue to track @rschristian's warning/error message suggestion. For anyone interested, it should be possible to add the warning to the [node-builtins-plugin.js](https://github.com/preactjs/wmr/blob/master/src/plugins/node-builtins-plugin.js). IIRC a list of built-in modules is available via `import { builtinModules } from 'module'`.

**Comment by dbetteridge** [comment]
I'm happy to take a stab at actually adding the helpful message, will go read up on rollup plugins.

**Comment by dbetteridge** [comment]
@developit @rschristian 
Would it be preferable to use 
1) this.warn allowing for the modules to be stubbed but not providing  dependency you're using doing the import/line number etc.
or 
2) this.error , which will inform you what dependency you're using that is causing the issue in addition to the specific module that is being called. 
But meaning that no stub is returned.

**Comment by developit** [comment]
Hmm, great question. I think I slightly prefer `this.error()` since it's unlikely code will be able to run properly with just the stub.
