### ISSUE TITLE
WMR isn't bundling my JS at all?

### ISSUE THREAD

**Issue by groundhogs** [preactjs/wmr#230]
WMR isn't bundling my code... What am I doing wrong?

I set this structure up: : 
```
public
> index.html
> assets
> > js
> > index.js
> > context.js
> > > util
> > > > console.js
> > css
> > > index.scss
```
The content of my files is: 
```html
<!DOCTYPE html>
<!-- public/index.html -->
<html>
	<head>
		<link rel="stylesheet" href="/assets/css/index.scss" />
	</head>
	<body>
        	<p>Hi</p>
		<script type="module" src="/assets/js/index.js"></script>
	</body>
</html>
```

```scss
// public/assets/css/index.scss
html,
body {
	background: #deadbeef;
	p {
		font-size: 2rem;
	}
}
```

```js
// public/assets/js/context.js
export const ENVIRONMENTS = {
	DEVELOPMENT: 'development',
	PRODUCTION: 'production'
};

const context = {
	ENVIRONMENT: ENVIRONMENTS.DEVELOPMENT
};

export default context;
```

```js
// public/assets/js/util/console.js
import ctx, { ENVIRONMENTS } from '../context';

const { ENVIRONMENT } = ctx;

const consoleShims = [ 'log', 'warn', 'error' ]
	.map((fn) => ({
		fn,
		shim: (...args) => {
			if (ENVIRONMENT === ENVIRONMENTS.DEVELOPMENT) {
				console[fn](...args);
			}
		}
	}))
	.reduce(
		(all, cur) => ({
			...all,
			[cur.fn]: cur.shim
		}),
		{}
	);

export default function getFor(component) {
	if (component instanceof Function) {
		component = component.name;
	}
	const componentShim = {};
	for (const [ name, fn ] of Object.entries(consoleShims)) {
		componentShim[name] = fn.bind(consoleShims, `[${component}]`);
	}

	return componentShim;
}

```

```js
// public/assets/js/index.js
const _console = require('./util/console');
const console = _console.getFor('WMR example');

alert(1);

console.log('Initializing');
```

What can be going on? I was expecting some kind of error at some point but what's currently happening is the SCSS is being transpiled correctly but my bundle isn't anywhere to be seen 😢 

*EDITED TO ADD* 

So, I understand that if I add the corresponding <script type="module"> tags and replace the requires with imports it does work. It just produces a JS structure that requires browsers to understand modules. But I was hoping for a bundling solution here? One that would allow me to ship a single file with all my stuff in it. Is WMR not that?

*EDITED TO ADD* 

Also, what I find in the `/dist` dir is... weird: 
![image](https://user-images.githubusercontent.com/11152449/101243821-831a1c00-36e1-11eb-9ea3-1f5f605d5de5.png)

Why is /assets duplicated? why is my compiled css inside its own /assets/assets but the JS in there isn't?

**Comment by developit** [comment]
Ah - WMR actually uses `assets/` to output compiled JS and CSS chunks, so creating your own assets folder is mixing things up. We can probably fix this, but for the time being just use a different directory name within `public` - something like `public/js`.

**Comment by groundhogs** [comment]
Will do! I'll report back shortly

**Comment by developit** [comment]
I think we can actually do one better - if you have your own assets directory, we'll generate a different one.

**Comment by developit** [comment]
One thing to note: WMR does not allow using CommonJS require() in source code - it's only allowed in `.cjs` files and `node_modules`. You should change your `index.js` to this:


```js
// public/assets/js/index.js
import getFor from './util/console.js';
const console = getFor('WMR example');

alert(1);

console.log('Initializing');
```

**Comment by groundhogs** [comment]
Ohhhh that's important! I'll do that too.

**Comment by groundhogs** [comment]
So, can confirm: 
- In "development" mode, no visible bundling occurs, my index.js ends up looking like this: 
![image](https://user-images.githubusercontent.com/11152449/101259767-ace73900-3709-11eb-96b9-2b8b73f67af2.png)
But everything is loaded correctly and works great which is amazing. 
- on "build" the expected output is indeed bundled and fine, which is I must say *pretty cool*!

Now I just need to figure out how to tell Rollup to use regenerator and the appropiate shims but that's on me 🤣 Thank you!
