### ISSUE TITLE
HMR doesn't work on Render's root component

### ISSUE THREAD

**Issue by mattlockyer** [preactjs/wmr#246]
Changing anything inside App component, does not "hot reload".

e.g. Hello Foo -> Hello World / Test -> Test Bar (changed reflected only after manually refreshing page)
```
function App() {
    return <>
        <h1>Hello Foo!</h1>
        <div>
            <p>
                Test
            </p>
        </div>
        <Test />
    </>;
}
```

Changing contents of Test component (code not shown) works fine, hot reloaded.

**Comment by developit** [comment]
Hiya - this will get fixed once we integrate the Babel portion of [prefresh](https://github.com/jovidecroock/prefresh). For now though, you can use `preact-iso` to make it work by default:

```diff
-import { render } from 'preact';
+import { hydrate } from 'preact-iso';

function App() {
    return <>
        <h1>Hello Foo!</h1>
        <div>
            <p>
                Test
            </p>
        </div>
        <Test />
    </>;
}

hydrate(<App />);
```

**Comment by mattlockyer** [comment]
Odd... adding export to main component makes it work... Bizarre!
```
export function App() {
	return <h1>Hello World</h1>;
}
```

**Comment by sortofsleepy** [comment]
Apologies for the possibly silly question -
I'm running into a similar problem here; but with child components. Like Matt noted, I had to add `export` to the component being put into `render`/`hydrate`  but I am finding that changes to child components don't appear to register. Take for instance

```javascript
....
export function App(){
    return <main>
        <Home/>
    </main>
}
hydrate(<App/>)
```

If I change the `Home` component, the change is not noted or written; even if I refresh, the last thing from the cache gets loaded. 

Any ideas? 

Not sure if it matters but in case it helps, running on Windows without using WSL(which has it's own issues apparently but not a requirement for my project)

**Comment by developit** [comment]
@sortofsleepy that seems like a different issue, perhaps relating to watching files on Windows. Do you see any logs in the console at all when saving the file?

**Comment by sortofsleepy** [comment]
> 
> 
> @sortofsleepy that seems like a different issue, perhaps relating to watching files on Windows. Do you see any logs in the console at all when saving the file?

I was wondering if that was the case at first but thought it was weird that I was still seeing it after going back to the native Windows command prompt. In any case no errors appear or anything like that as far as I can tell; things just don't refresh.

**Comment by davidmz** [comment]
I have the same issue as @sortofsleepy (also on Windows). No messages appear in the console. How can I turn on some debug output?

**Comment by JoviDeCroock** [comment]
I've just tried our latest commit on Windows (no WSL) and this issue seems resolved, the root component not re-rendering without exporting the function is normal. We'll need to integrate with the `Prefresh Babel plugin` to make that work.

**Comment by davidmz** [comment]
I have the following structure:
```
public
└ index.html
└ index.tsx
└ components
  └ App.tsx
```
index.tsx imports components/App.tsx and wmr doesn't track changes in App.tsx.

When I move App.tsx up to the 'public' folder, it starts tracking normallly.

**Comment by JoviDeCroock** [comment]
I'll check it out, thanks for the explanation

**Comment by davidmz** [comment]
I think I found the root of my issue. As we know, Windows uses `\` as the path separator. The wmrMiddleware uses file paths as keys of WRITE_CACHE. It [creates entries](https://github.com/preactjs/wmr/blob/37fa3c218d0ed3f22a93ef2f2e7ec200bc6b3489/src/wmr-middleware.js#L471) with the native OS separators **but** [deletes](https://github.com/preactjs/wmr/blob/37fa3c218d0ed3f22a93ef2f2e7ec200bc6b3489/src/wmr-middleware.js#L128) them with the POSIX (`/`) separators.

As a result, when a file with a separator in the name is updated, WMR cannot remove the correct entry from WRITE_CACHE and emits the old content.
