### ISSUE TITLE
Typescript error for css module imports

### ISSUE THREAD

**Issue by ivancuric** [preactjs/wmr#259]
Using the default demo template, I get the following error in any `index.js` file when importing from css (modules):

```
Cannot find module './style.module.css' or its corresponding type declarations.
```

I recommend using a d.ts file for common non-js imports like CRA does:
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/lib/react-app.d.ts

**Comment by marvinhagemeister** [comment]
That's strange because we already do have such a type file here: https://github.com/preactjs/wmr/blob/master/types.d.ts

**Comment by ivancuric** [comment]
What's interesting is that I don't seem to have _any_ typing available. Everything is either inferred default types or `any`.

Eg [ `About` ](https://github.com/preactjs/wmr/blob/d7faaad9f6a2af6a4fcce34669cb296979e8b2ea/demo/public/pages/about/index.js#L3) is inferred as:
```ts
const About: ({ query }: {
    query: any;
}) => any
```

**Comment by developit** [comment]
Hiya - any chance you have a custom `tsconfig.json` instead of using `create-wmr` to generate the project? We do ship a d.ts file for this as marvin mentioned, and it includes ambient declarations for `*.module.css`.

There is an issue where the imported value is incorrectly typed as `string` that is fixed on master but hasn't been released.

What version of TypeScript are you using? (local and/or vscode versions)

**Comment by developit** [comment]
One thing to check: I believe our ambient declarations require `moduleResolution: 'node'` in tsconfig's compilerOptions.

**Comment by ivancuric** [comment]
There is a `tsconfig.json` but it was generated using `create-wmr`. The whole folder was.
```json
{
	"compileOnSave": false,
	"compilerOptions": {
		"jsx": "preserve",
		"allowJs": true,
		"checkJs": true,
		// "strict": true,
		"noEmit": true,
		"moduleResolution": "node",
		"target": "ESNext",
		"module": "esnext",
		"resolveJsonModule": true,
		"allowSyntheticDefaultImports": true,
		"downlevelIteration": true
	},
	"typeAcquisition": {
		"enable": true
	}
}
```

**Comment by ivancuric** [comment]
Ok, I had `  "typescript.disableAutomaticTypeAcquisition": true,` enabled in VScode for some reason.

Now two projects using `create-wmr` are reporting different errors.

**Comment by Marabyte** [comment]
I was going to open a PR but it seems the code on master will fix this issue.

I think the issue @ivancuric and I are seeing is related with the order ambient modules are declared.
This is the order I'm getting with wmr@1.0.0 :
```typescript
// types.d.ts
declare module '*.css' { const url: string; export default url; }
declare module '*.scss' { const url: string; export default url; }
declare module '*.sass' { const url: string; export default url; }
declare module '*.styl' { const url: string; export default url; }

/** Maps authored classNames to their CSS Modules -suffixed generated classNames. */
interface Mapping { [key: string]: string; }
declare module '*.module.css' { const mapping: Mapping; export default mapping; }
declare module '*.module.scss' { const mapping: Mapping; export default mapping; }
declare module '*.module.sass' { const mapping: Mapping; export default mapping; }
declare module '*.module.styl' { const mapping: Mapping; export default mapping; }
```
But on master the order is correct. (which is a bummer, I was eager to make a splash with an easy fix PR )

**Comment by Marabyte** [comment]
> A newly created one can't seem to get typings for `preact/hooks` and there are errors when accessing CSS modules:

This is a different issue (or feature).
`preact` is installed locally if you run `npm run build` but not by default. `preact-iso` lists `preact` as a `dev-dependency` which is why it's not installed when you `npm install` on a `wmr` template project.

**Comment by rschristian** [comment]
> This is a different issue (or feature).
> `preact` is installed locally if you run `npm run build` but not by default. `preact-iso` lists `preact` as a `dev-dependency` which is why it's not installed when you `npm install` on a `wmr` template project.

Yeah, we noticed that yesterday and this was fixed with #256

**Comment by developit** [comment]
Ah thanks for clarifying that @Marabyte, I hadn't realized it was because of the peerDependencies thing. `preact-iso` is correct in that regard, we just needed to have `create-wmr` do the right thing as @rschristian mentioned. 

We'll get a release out today that sorts these things out.

**Comment by developit** [comment]
Hiya! This just got released in `wmr@1.1.0`. Update the dependency and you should see the corrected types.

**Comment by Paratron** [comment]
I just wanted to note that I created a new WMR project with `npm init wmp whatever` a couple of minutes ago and I have the exact same error in the provided example code:

![grafik](https://user-images.githubusercontent.com/902599/112228458-9cfc5200-8c31-11eb-8517-7aab5565b7a0.png)

**Comment by rschristian** [comment]
@Paratron Unfortunately that's an issue with the way JetBrains handles types. I raised the issue a few months back, but they have no interest in fixing it. I ended up switching away from their products shortly after. You can add a dummy `import 'wmr';` to say your `index.js` to remove the error.

**Comment by Paratron** [comment]
I dont understand how this is related to the IDE. It calls tsc and displays the output so this should rather be an typescript configuration problem than an IDE issue. Its not like intelliJ does its own TS parsing.

But nevermind - I just wanted to leave the note. I already removed WMR again.

**Comment by rschristian** [comment]
@Paratron It's tied to the IDE as JetBrains have chosen a homemade approach to how they handle most things. You can't use the generic language servers as they argue they can do it better. This of course has advantages and disadvantages. This would be one of the disadvantages. 

> It calls tsc and displays the output

Not exactly, no. Calling `tsc` on a project would be very, very expensive and slow to do. 

>  Its not like intelliJ does its own TS parsing.

It does actually. This error doesn't exist if you run TSC. Feel free to try it with `tsc --noEmit`. Note that other errors will arise, as this is a JS template and a few funky things are done that can only be done in JS. There are TS workarounds for those, but I digress.

**Comment by danielweck** [comment]
@Paratron try adding this to your `tsconfig.json`:
```
"files": ["./node_modules/wmr/types.d.ts"]
```
