### ISSUE TITLE
[preact-iso] Why `useLoc` instead of `useLocation`?

### ISSUE THREAD

**Issue by joaopaulobdac** [preactjs/wmr#269]
Official hooks generally aren't named like this. Is it temporary or was there some issue with using `useLocation`?

Great project by the way, it was super quick to set everything up, right now I'm waiting for the preact-iso type definitions to be released.

**Comment by developit** [comment]
Heh - yeah this is a good point. The router was initially called "Loc" and thst gave way to the hook name. We can change it though, we'll just alias for a version.
