### ISSUE TITLE
preact-iso (type declarations not included or missing)

### ISSUE THREAD

**Issue by sync** [preactjs/wmr#284]
If you explore the repo from there: https://www.npmjs.com/package/preact-iso (explore tab) you can see that none of the `.d.ts ` files are included.

<img width="800" alt="Screen Shot 2020-12-23 at 1 39 46 pm" src="https://user-images.githubusercontent.com/21725/102953039-8f490a80-4524-11eb-97ad-85bc59ac994d.png">

Which is obviously making typescript unhappy:

<img width="858" alt="Screen Shot 2020-12-23 at 1 42 09 pm" src="https://user-images.githubusercontent.com/21725/102953111-ae479c80-4524-11eb-94bf-3a4ca566867e.png">

Is there a reason for not including those or is it just an oversight ? Also how can I help ?

**Comment by developit** [comment]
Hiya - this is actually just because we haven't published `preact-iso` since landing the types.

**Comment by sync** [comment]
yes sorry was just about to say it will be there next publish. Sorry :-)

**Comment by developit** [comment]
All good!
