### ISSUE TITLE
Dynamic imports with dynamic file name issues

### ISSUE THREAD

**Issue by enjikaka** [preactjs/wmr#286]
I'm having a few issues with dynamic imports where the file name is dynamic.

If I `await import(`./pages/${pageName}.js`)` then the import works in dev mode but fails in the build on the error `TypeError: Failed to fetch dynamically imported module: http://localhost:8080/pages/home-page.js`. Here the import path obviously ends up wrong in the build.

If I then change that path to work in the build, to `await import(`/js/pages/${pageName}.js`)`, then it seems like WMR finds it, but then it fails at loading its NPM dependencies? This import variant also works in dev mode, but fails in the build with: `TypeError: Failed to resolve module specifier "webact". Relative references must start with either "/", "./", or "../".` (webact here is an NPM dependecy). Which also makes sense since it's not a valid import.

How can this be handled to work in both dev and prod?

**Comment by developit** [comment]
Hiya @enjikaka! I think we should be able to address this for the most common cases by adding [@rollup/plugin-dynamic-import-vars](https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars) to WMR's production setup. If you have a test project, try adding that plugin using `wmr.config.js`:

```js
// wmr.config.js
import dynamicImportVars from '@rollup/dynamic-import-vars';

export function build(config) {
  config.plugins.push(dynamicImportVars());
}
```

Your initial code should now work on both dev and prod:

```js
await import(`./pages/${pageName}.js`);
```

**Comment by enjikaka** [comment]
I'll try it out. Thanks!

Den mån 28 dec. 2020 16:54Jason Miller <notifications@github.com> skrev:
