### ISSUE TITLE
Controlling the publicPath in the index.html page

### ISSUE THREAD

**Issue by keul** [preactjs/wmr#287]
I tried using this tool for a quick way to deploy a small demo but I did not found a way to control the deploy base path used by resources in index.html

My deploy URL is something like https://xxx.github.io/project/

Looking at source code and few documentation available I found references to `publicPath` usage in the `wmr.config.js` file, but it is not working (at least not for this).

MY HTML file is something like this:

```	<link rel="icon" href="/favicon.png">
	<link rel="preload" as="script" href="./index.js" crossorigin>
	<link rel="stylesheet" href="/style.css">
</head>

<body>
	<script type="module" src="/index.js"></script>
	```

But final HTML file generated in build directory is always root based.

**Comment by rschristian** [comment]
I believe this was addressed by #213, just hasn't been released yet.

**Comment by keul** [comment]
Thanks, so this has ben fixed. This can be closed.

I hope that something will be added in the documentation too. Right now there's a "See the full list of options" link to an undocumented Typescript source containing a list of options… not documentation IMHO.

**Comment by rschristian** [comment]
@keul The list of options probably isn't ideal but does work as a stand-in for now. PRs are always welcome of course if you have an idea of how we might document that well.

**Comment by keul** [comment]
> @keul The list of options probably isn't ideal but does work as a stand-in for now. PRs are always welcome of course if you have an idea of how we might document that well.

That's the problem: there's not way to know how those options works without testing and debugging code.
For example: I believed that `publicPath` would have worked for me so I spent an hour trying to understand why it was not working for me, then I switched to changing "public" (which I understand later is a totally different options, maybe for the "public folder"?).

BTW: no offense here, I love this kind of tools and the work behind them, but I had the same issue with microbundle: the promises of "something simple" has been broken by hitting a wall of "no idea how to use this in a real world case".
So I just switched to plain rollup.

**Comment by rschristian** [comment]
> For example: I believed that `publicPath` would have worked for me so I spent an hour trying to understand why it was not working for me, then I switched to changing "public" (which I understand later is a totally different options, maybe for the "public folder"?).

Sorry, the feature has been merged, but this is rather newly made public and it's around the holidays; people are spending time elsewhere at the moment. PRs are always open if you want to use your experience to improve the project though.

**Comment by keul** [comment]
@rschristian sorry my note was not about this feature specifically, and I perfectly know it's Christmas (I was not expecting any reply before late January!).

Just a general average documentation rant in the programming world. 😄 

Sorry for going off-topic, and thanks again for the reply.
