### ISSUE TITLE
Using absolute imports within project

### ISSUE THREAD

**Issue by rschristian** [preactjs/wmr#289]
As the title suggests, I'm wondering if it's possible to use absolute imports given the nature of the automatically installed NPM modules.

Just for clarity, given the following directory structure, I'd like `index.js` to be able to import `header.js` via `import ... from 'components/header';`. Absolute imports with "public" as a base directory being assumed.

```
public/
--components/
----header.js
--index.js
```

I tried out a few Rollup plugins that were supposed to add that functionality (`rollup-plugin-includepaths` and `@rollup/plugin-node-resolve`) as well as rebuilding from source with an edit to the existing `node-resolve` plugin though I couldn't get any of those to work. Certainly possible it's user error, though it seems WMR will fall back to installing rather than use the plugins. Not entirely sure why.

I can only speak for myself but I know this is something I immediately add in every tool. I imagine some other users would look for this too, so probably a worthwhile addition to [the recipes](https://github.com/preactjs/wmr#recipes) if it is something that's possible currently. I'll certainly keep playing around with this but I thought I'd throw in this issue now.

**Comment by developit** [comment]
@rschristian this would require a leading `/` or sigil of some kind, like `~/components/header`. Without that, it's impossible to distinguish between `components/header` being a filesystem path VS a `header` export within a module `components`.

I think we could show a recipe for `~/*` pointing to `public/`, I'll try to noodle on one. Something like this should work in both dev and prod:

```js
// wmr.config.js
import path from 'path';
export default function(config) {
  // allow `import '~/foo/bar.js'` relative to public dir:
  config.plugins.push({
    name: 'root-resolve',
    resolveId(spec, importer) {
      if (!spec.startsWith('~/')) return;
      return path.resolve(config.cwd, spec.substring(2));
    }
  });
}
```

**Comment by rschristian** [comment]
That's (roughly) what I had fallen back into doing, certainly gets the job done. 

Thanks for the response, glad I wasn't missing something.

**Comment by rschristian** [comment]
@developit I wonder, should this come out of the box, rather than being a config to copy/paste? I can't imagine this would cause any conflicts. Regardless, I have this worked up in a PR, can alter it there if we want.

**Comment by developit** [comment]
I am (for reasons I should probably revisit) not a huge fan of project aliases. They require configuration to unbreak tools like typescript and IDEs, and it's sort of a step away from lightly nudging folks towards writing JS that is close to running as-is.
