### ISSUE TITLE
Sass @use and @import does not work with hot reload

### ISSUE THREAD

**Issue by kasperstorgaard** [preactjs/wmr#291]
Hi there

I was playing around with wmr and sass for a personal project, and it seems that hot reloading breaks when using `@use` or `@import` to split the styles into multiple files.

I created a demo repo: 
https://github.com/kasperstorgaard/wmr-sass-tester

and a recording:
![wmr-sass-tester](https://user-images.githubusercontent.com/3033516/103453865-8bfd0e00-4cde-11eb-9a17-a313da249294.gif)
https://user-images.githubusercontent.com/3033516/103453681-a59d5600-4cdc-11eb-99f8-1096e1f0a6b5.mov

---
Notes:
* The sass support is not documented anywhere as far as I can tell, whats the plan with that going forward?
* I really want to go closer to the platform, and not use sass at all, but I have a design token setup, where looping is a must. (I guess the other option would be to split it into a separate package, or to use parallel build setup)

**Comment by developit** [comment]
Hmm, interesting. I'm not 100% sure where, but it seems like we're failing to process sass at all during HMR updates.

**Comment by kasperstorgaard** [comment]
Seems to be fixed, thanks!
