### ISSUE TITLE
use/hook into prerender to build static html?

### ISSUE THREAD

**Issue by smeijer** [preactjs/wmr#305]
Is there a way to use the prerender functionality to build static html that could run without javascript?

Let's say I'm using an API in dev mode to render a list with blogs. But when I publish (build) the site, I don't want to keep this list dynamic. Instead, I just want to serve a static HTML file, that would also run without javascript.

Reason I ask, is because if this would be possible, we could also call private API's during development while serving the content statically once the site has been build & published. (not exposing api keys).

To update the site, one could then simply make a CI/CD pipeline to rebuilt de site on a regular basis or by using webhooks.

**Comment by smeijer** [comment]
Ok, this is exactly what `prerender` does; _create HTML from dynamic js_. But what's unclear to me, is what the pattern would be to fetch the data from an API during prerender.

**Comment by JoviDeCroock** [comment]
Hey,

I think the best way to look at it is that it will use a `suspense-like` mechanism, basically if we look at how [`lazy`](https://github.com/preactjs/wmr/blob/master/packages/preact-iso/lazy.js) works we see that a promise is thrown upwards and subsequently resolved.

We'd need to implement a mechanism similar to `(p)react-ssr-prepass` as showcased in [this demo](https://github.com/JoviDeCroock/realworld) this would allow us to throw `data-promises` upwards, resolve them and rerender with the needed data.

I think this should be feasible given our current architecture, do note that this would probably need to remove JS entirely or have a separate hydration bundle or we'll also be suspending on the client, which from what I can derive isn't what you want.

**Comment by zhenyanghua** [comment]
I was researching for ways to prerender the the `title` and `meta` tags in the `head` and found this issue.
Currently I have a hook to set the page title:
```js
export function useTitle(title) {
  useEffect(() => {
    document.title = `${title ? title + ' - ' : ''}Home`;
  }, []);
}
```
Eventually I also want to inject the `meta` tags to the `head`, however, based on the current `prerender` [implementation](https://github.com/preactjs/wmr/blob/87581b2ba5599aff5e09d711a48d24757a3e53be/src/lib/prerender.js#L133), it seems it only injects the CSS to the head, not anything else. 
 
@JoviDeCroock What do you have in mind to allow us to update `title` and inject `meta` to the head during prerender?

**Comment by developit** [comment]
@zhenyanghua we're thinking about adding support for injecting HTML into the document head during prerendering via `document.head.innerHTML=''`.

**Comment by zhenyanghua** [comment]
@developit thanks for the info and great work! Is there a proposal for it? Can I take a sneak peak at how the draft API may look like?

**Comment by developit** [comment]
@zhenyanghua I ended up implementing this in #330:

```js
// set the page title:
document.title = 'This will become the <title> element contents!';

// you can also inject custom HTML into head:
document.head.insertAdjacentHTML(
  'beforeend',
  '<meta property="og:title" content="How to Become an SEO Expert">'
);
```
