### ISSUE TITLE
Are web worker imports available?

### ISSUE THREAD

**Issue by jorbuedo** [preactjs/wmr#317]
As the title says, how can I make web workers work?
In preact-cli I used `worker-loader!` as a prefix for the import and that gave Worker for that script.
I've seen there's a recipe for Service Workers, but I don't thing that applies to normal workers.

Does this need the use of a rollup plugin here?

**Comment by developit** [comment]
Hiya! You should be able to do this:

```js
import url from 'bundle:./path/to/worker.js';

const worker = new Worker(url, { type: 'module' });
```

In production this will rely on Module Workers, which aren't perfectly supported everywhere. To fix that you could use a [module workers polyfill](https://www.npmjs.com/package/module-workers-polyfill) (YMMV) or the [rollup-plugin-off-main-thread](https://github.com/surma/rollup-plugin-off-main-thread) plugin.

**Comment by jorbuedo** [comment]
That did the trick! Thank you. 
Support is not a concern for now, but I'll keep the polyfills in mind. 

Maybe this example should be added to the docs?

**Comment by jorbuedo** [comment]
Btw I cannot find the proper way for typescript to understand the file is a module: `File 'xxx/init.ts' is not a module.ts(2306)`
The code is found and it works, it just has that warning and my google-fu isn't being enough. This is my tsconfig.json right now:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": "public",
    "checkJs": true,
    "downlevelIteration": true,
    "jsx": "preserve",
    "jsxFactory": "preact.h",
    "jsxFragmentFactory": "preact.Fragment",
    "lib": ["ESNext", "WebWorker"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "paths": {
      "~/*": ["*"],
      "bundle:~/*": ["*"]
    },
    "resolveJsonModule": true,
    "strict": true,
    "target": "ESNext"
  },
  "typeAcquisition": {
    "enable": true
  }
}
```

**Comment by JoviDeCroock** [comment]
Hey @jorbuedo is this still an issue? If so let's create a separate issue for it, I've added web-workers to the wiki to document the approach @developit described.

The issue you describe there seems quite editor related, might wanna try to copy our `tsconfig`, I think `allowJS` and `strict` sometimes interfere.
