### ISSUE TITLE
Add support for private registries

### ISSUE THREAD

**Issue by sventschui** [preactjs/wmr#319]
Add support for `.npmrc` and private registries.

1. API in https://github.com/preactjs/wmr/blob/71b80e0a89060c6d8d2c3b72ff9dcbbff9ef12e8/src/plugins/npm-plugin/registry.js#L54 should not be hardcoded but rather resolved by looking for a `.npmrc` file up in the tree and resolve the registry from there. This should also support registries specified for certain scopes. Related to https://github.com/preactjs/wmr/issues/167
2. Add support for authenticated registries. Use credentials from `.npmrc` or ask for it in interactive mode

See https://github.com/yarnpkg/yarn/blob/a4708b29ac74df97bac45365cba4f1d62537ceb7/src/registries/npm-registry.js for some inspiration

**Edit:** A "simple" solution could be to run `npm config list --json` and parse its JSON output. It will give the registry config in the `registry` and `@<scope>:registry` keys. Also it provides `userconfig` and `globalconfig` keys that can be used to try to lookup auth tokens in these files. Also `<registry_url>:always-auth` keys should be respected to send credentials when trying to resolve packages.

**Comment by marvinhagemeister** [comment]
Let's track this in #167 👍
