### ISSUE TITLE
WMR serve - routing glitch

### ISSUE THREAD

**Issue by antonsamper** [preactjs/wmr#333]
I have followed the install and build process but when I then run the app using `wmr serve`, upon visiting the page in the browser (http://localhost:8080/), I'm experiencing some strange behaviour as i switch between routes.

Im using node v14.15.4 and i haven't modified any of the files. It feels like the previous route content doesn't disappear until the new route is loaded?

https://user-images.githubusercontent.com/102233/107158467-1d1c7000-6982-11eb-9556-1de218924984.mov

**Comment by developit** [comment]
Hiya! This is actually mostly the intended behavior - routes are only unloaded when the new one has downloaded and ready to render (avoiding a "flash of white page").  The funky double-rendering thing is #221, hopefully we'll have a fix soon.

**Comment by developit** [comment]
@antonsamper Just to check if I've understood correctly - does the glitch described in #221 match what you wanted to create an issue about? Or did you have a concern relating to the previous route not being unloaded immediately when clicking a link?

**Comment by antonsamper** [comment]
Hi @developit , thanks for the quick reply! The issue I'm describing is in fact the same as #221 , i just hadn't spot it 😄  Thanks for the additional details too, I'm familiar with `lazy` but not so much with `preact-iso` so its quite interesting to see the `path` attribute being used with `ErrorBoundary`.
