### ISSUE TITLE
Change README

### ISSUE THREAD

**Issue by mikhaylenko** [preactjs/wmr#334]
Please, change description in your README. 

`The tiny all-in-one development tool for modern web apps, in a single 2mb file with no dependencies."`

**2mb** - it's so much )

Thanks

**Comment by JoviDeCroock** [comment]
Hey, have you compared this size to other dev-tools most are over 20mb

**Comment by developit** [comment]
| tool | size | note
|---|---|---
@vue/cli | [![install size](https://packagephobia.com/badge?p=@vue/cli)](https://packagephobia.com/result?p=@vue/cli)
create-react-app | [![install size](https://packagephobia.com/badge?p=react-scripts)](https://packagephobia.com/result?p=react-scripts)
preact-cli | [![install size](https://packagephobia.com/badge?p=preact-cli)](https://packagephobia.com/result?p=preact-cli)
Next.js | [![install size](https://packagephobia.com/badge?p=next)](https://packagephobia.com/result?p=next)
Vite | [![install size](https://packagephobia.com/badge?p=vite)](https://packagephobia.com/result?p=vite)
Snowpack | [![install size](https://packagephobia.com/badge?p=snowpack)](https://packagephobia.com/result?p=snowpack) | _19mb with officially recommended setup_
Webpack | [![install size](https://packagephobia.com/badge?p=webpack)](https://packagephobia.com/result?p=webpack) | _+26mb for bare minimum plugins_
Rollup | [![install size](https://packagephobia.com/badge?p=rollup)](https://packagephobia.com/result?p=rollup) | _+6mb for bare minimum plugins_
WMR | [![install size](https://packagephobia.com/badge?p=wmr)](https://packagephobia.com/result?p=wmr)

**Comment by mikhaylenko** [comment]
Thank you for your full answer. 
Maybe I understand wrong about this size. 

For Preact its `Fast 3kB alternative to React with the same modern API.`

**Comment by JoviDeCroock** [comment]
Preact is a tool to render UI, this is a tool to develop these applications. There is a big difference between the two since the latter has to analyze, bundle and minify code.
