### ISSUE TITLE
Image optimization

### ISSUE THREAD

**Issue by JoviDeCroock** [preactjs/wmr#356]
Currently we aren't really leveraging any asset pipeline-y features, we could improve on this by adding some plugins that can do production optimization of images.

For example we can run images through [`squoosh`](https://www.npmjs.com/package/@squoosh/cli) and transform everything into `webp`/... This could help reduce the size of published applications.

[Support in Safari for WebP still seems flakey](https://caniuse.com/?search=webp)

**Comment by vimtor** [comment]
Maybe doing something like `next/image` will be a related alternative. 

Just optimizing the asset is fine but things like serving smaller images in small devices or lighter ones in devices with few DPRs can only be done at the HTML level.

Perhaps the plugin @JoviDeCroock mentioned could also alter the HTML, but seems quite magic to me :smile:
