### ISSUE TITLE
Unprocessed scss file gets copied over to dist during build

### ISSUE THREAD

**Issue by zgoda** [preactjs/wmr#361]
I have local font definitions imported from `style/fonts.scss` in `style/main.scss`.

```console
$ tree public
public
├── app.js
├── assets
│   └── fonts
│       ├── lato-v17-latin-ext_latin-italic.woff
│       ├── lato-v17-latin-ext_latin-italic.woff2
│       ├── lato-v17-latin-ext_latin-regular.woff
│       └── lato-v17-latin-ext_latin-regular.woff2
├── index.html
├── index.js
└── style
    ├── fonts.scss
    └── main.scss
```

Build properly builds css and puts content into single minified file, but leaves unprocessed `style/fonts.scss` in `dist`:

```console
$ tree dist
dist
├── assets
│   ├── fonts
│   │   ├── lato-v17-latin-ext_latin-italic.woff
│   │   ├── lato-v17-latin-ext_latin-italic.woff2
│   │   ├── lato-v17-latin-ext_latin-regular.woff
│   │   └── lato-v17-latin-ext_latin-regular.woff2
│   └── main.e75a073a.css
├── chunks
│   └── prerender.8ab96da0.js
├── index.13d2992f.js
├── index.html
└── style
    └── fonts.scss
```

**Comment by JoviDeCroock** [comment]
Hey,

How do these files relate, does main.scss import the fonts file or? Need to know this if we want to reproduce this ourselves.

**Comment by rschristian** [comment]
Duplicate of #254 I believe

**Comment by zgoda** [comment]
main.scss:

```
@import './fonts.scss';
```

**Comment by zgoda** [comment]
In case of SCSS the import is properly resolved by SASS upon processing and the resulting css file is perfectly valid.

**Comment by rschristian** [comment]
@zgoda So just a leftover file then? Functionally everything is working as you'd expect?

**Comment by zgoda** [comment]
Apart of https://github.com/preactjs/wmr/issues/291 evetything seems to work fine. ;)
