### ISSUE TITLE
Pre-render creates dist folder names that include route query params if present in a@ref links

### ISSUE THREAD

**Issue by danielweck** [preactjs/wmr#392]
To reproduce the bug, change the `a@href` attribute in:

https://github.com/preactjs/wmr/blob/42fa94027c0adc05b1e05b364010eb39203a12e8/packages/wmr/demo/public/header.tsx#L9

to: `<a href="/about?key=val&k=v&k1=a+b&k2=c%20d#hash">About</a>`

Then, `npm run build` shows:

```
Prerendered x pages:
  /
...
  /about?key=val&k=v&k1=a+b&k2=c%20d [from /]
...
```
... and the `dist` folder contains a subfolder named `about?key=val&k=v&k1=a+b&k2=c%20d` (it should be `about`).

To verify this in the browser, I added a `setTimeout()` of 2 seconds around the `hydrate()` call, and I modified some text in the pre-rendered HTML inside the `dist` folder, so that the transition from server-prerendered pages to client-side dynamic state is obvious. The `about` page with query params fails to load at first render, but displays correctly after `hydrate`.

PS: note that the demo doesn't include a `hydrate` call, I think that's a separate error:
https://github.com/preactjs/wmr/blob/42fa94027c0adc05b1e05b364010eb39203a12e8/packages/wmr/demo/public/index.tsx#L46-L48

**Comment by developit** [comment]
Good catch!
