### ISSUE TITLE
Pulling files from package's parent directory

### ISSUE THREAD

**Issue by urish** [preactjs/wmr#394]
First of all, thanks again for creating wmr! It's lightweight & quick, so I don't have to think twice before using it in a project :-)

## Desired outcome

I'm trying to achieve a setup where there's a small demo project inside my [library's repo](https://github.com/wokwi/fastled-monaco).

The demo project resides in `/demo`, and it needs access to files from the library. I want to use the full library name ("@wokwi/fastled-monaco") in the imports. The idea is to keep the demo code consistent with how users would eventually import the package, while using the local sources so potential contributors can make changes and see the result immediately.

## wmr build

Getting it to work with `wmr build` was fairly easy - I only had to add an alias to my `package.json` and it worked right away:

```json
  "alias": {
    "@wokwi/fastled-monaco": "./../src"
  }
```

## wmr start

The development server was a completely different story. I spent half a day stitching together pieces of examples and hacked together a custom plugin that somehow makes it works:

```js
import { promises as fs } from 'fs';
import { dirname, join, resolve } from 'path';
import { fileURLToPath } from 'url';
import typescript from 'typescript';
const { transpile } = typescript;

const __dirname = dirname(fileURLToPath(import.meta.url));
const parentSrc = resolve(join(__dirname, '..', 'src'));

function parentProjectPlugin(options) {
  options.plugins.push({
    name: 'parent-project',
    async resolveId(id, importer) {
      if (options.mode === 'build') {
        return;
      }
      if (id === parentSrc) {
        return '\0parent-project:/@fastled-monaco/index.ts';
      }
      if (importer && importer.startsWith('\0fastled-monaco:') && !id.endsWith('.ts')) {
        return id + '.ts';
      }
    },
    async load(id) {
      const prefix = '\0fastled-monaco:';
      if (id.startsWith(prefix)) {
        const relative = id.substr(prefix.length);
        const finalPath = resolve(parentSrc, relative);
        this.addWatchFile(finalPath);
        return transpile(await fs.readFile(finalPath, { encoding: 'utf-8' }), {
          target: 'es2020',
          module: 'es2015',
        });
      }
    },
  });
}

export default function (config) {
  parentProjectPlugin(config);
}
```

So I have a setup that works, but:

1. It's very likely to break at some point
2. I don't really understand what's going on there. For instance, why did I add the `\0` prefix? Why do I manually compile the TypeScript files instead of having them going through the sucrase plugin?
3. For some reason, the `addWatchFile()` doesn't do the trick. The page doesn't automatically refresh when I change files in the library's `src/` directory. The changes are picked up when I refresh the page, so this is still usable (but not ideal).

I don't know if this use case is common, but I'd love to have a simpler solution for this. Ideally this would just work out of the box like `wmr build` does, but some way to tell wmr to map `@wokwi/fastled-monaco` to a specific directory in disk would also be as good. 

Any pointers/hints would be much appreciated, and thanks again for making wmr!

**Comment by rschristian** [comment]
Is there any particular reason you don't just run `tsc -w ...` for your lib and then keep wmr for the demo? Can just symlink to `@wokwi/fastled-monaco` in your demo app then with `yarn/npm link`

Doing this would also ensure your demo was more "real world" as it's using the exact same build output that users would use in the wild. Not that I can foresee anything that wmr would do wildly different from tsc, but there is potential for that to be an issue.

I'm not positive, but I believe you need to do that all because what you want is not really what the alias field is for. It's meant so you can alias React to Preact in installed modules, for example. It assumes the alias is another compiled module, not more source code that needs to be compiled and watched. It wouldn't normally make any sense to watch `node_modules`, hence why you're running into issues. 

I believe you should be able to just create a plugin to rewrite imports, but will need to try that out myself first. Will get back to you on that.

**Comment by urish** [comment]
Ryan, thank you so much for taking the time to reply to me!

> Is there any particular reason you don't just run tsc -w ... for your lib and then keep wmr for the demo? Can just symlink to @wokwi/fastled-monaco in your demo app then with yarn/npm link

That's an interesting approach. I haven't explored it in depth, but the general idea is to have it as simple as possible to test your changes for people who want to contribute the code. So we could probably run `tsc -w ...` together with `wmr`, perhaps using `concurrently` so that the user only has to run a single npm script. I will have to look into that, as symlinks may not work correctly on Windows, and have to figure out how to get it to work with source maps correctly.

The fact that `alias` worked almost out of the box for the production build made me think this might be a good direction for the development setup as well. But reading your reply, it now seems to me that I'm going the wrong path.

I really appreciate your response. It's helpful.

**Comment by rschristian** [comment]
`yarn/npm link` should work fine for the symlinks. They'll ensure that the current build of your lib acts as though it was installed in your demo. Source maps will work right out of the box if you provide them (just a flag with tsc I believe).

**Comment by marvinhagemeister** [comment]
Closing as the aliasing feature has been rewritten a while back to allow aliasing directories. With that it's possible to include files from anywhere, see https://wmr.dev/docs/configuration#aliasing-and-path-mappings 🎉
