### ISSUE TITLE
packages/wmr/demo contains a hard copy of an old version of preact-iso lazy, prerender, and useLocation

### ISSUE THREAD

**Issue by danielweck** [preactjs/wmr#404]
Should this be replaced with `preact-iso` imports?

https://github.com/preactjs/wmr/tree/main/packages/wmr/demo/public/lib

**Comment by JoviDeCroock** [comment]
We use this for debugging, feel free to PR a way to symllink

**Comment by danielweck** [comment]
Apologies, I now realise that the `demo/public/lib/` JS files and the source `preact-iso` code are in sync:

* https://github.com/preactjs/wmr/blob/main/packages/preact-iso/lazy.js
* https://github.com/preactjs/wmr/blob/main/packages/wmr/demo/public/lib/lazy.js

* https://github.com/preactjs/wmr/blob/main/packages/preact-iso/router.js
* https://github.com/preactjs/wmr/blob/main/packages/wmr/demo/public/lib/loc.js

* https://github.com/preactjs/wmr/blob/main/packages/preact-iso/prerender.js
* https://github.com/preactjs/wmr/blob/main/packages/wmr/demo/public/lib/prerender.js
