### ISSUE TITLE
Automatically add .env file variables

### ISSUE THREAD

**Issue by damianobarbati** [preactjs/wmr#407]
**Feature proposal**
Automatically add `.env.<NODE_ENV>` envs when file `.env.<NODE_ENV>` is found.

```bash
echo NAME=ciao >> .env.development
NODE_ENV=development yarn wmr src/index.html 
# console.log(process.env.NAME) logs "ciao"
```

```bash
echo NAME=hello >> .env.staging
NODE_ENV=staging yarn wmr build src/index.html 
# console.log(process.env.NAME) logs "hello"
```

Inspired by parcel, easy declarative way to handle env variables.

I created `envk` entrypoint for node which does exactly this https://www.npmjs.com/package/envk
```bash
NODE_ENV=development node -r envk src/index.js
```

**Comment by JoviDeCroock** [comment]
Hey,

As far as I know we're currently doing this: https://github.com/preactjs/wmr/blob/425f07525d2010e89270d10856b9a35d4205d0a4/packages/wmr/src/lib/normalize-options.js#L30 this will merge the environment files based on presedence

**Comment by damianobarbati** [comment]
Sounds great, closing (later testing it!)
