### ISSUE TITLE
preact-iso/router uses string.trim() incorrectly to remove leading and trailing slashes

### ISSUE THREAD

**Issue by danielweck** [preactjs/wmr#414]
**Describe the bug**

Code references:

https://github.com/preactjs/wmr/blob/0833c4ad25ceffae461d4d8f8643744cc0b7e080/packages/preact-iso/router.js#L22-L23

and:

https://github.com/preactjs/wmr/blob/0833c4ad25ceffae461d4d8f8643744cc0b7e080/packages/wmr/demo/public/lib/loc.js#L22-L23

The current code does not actually remove leading and trailing slashes in `route` and `url`, resulting in the subsequent `.split()` call generating empty strings in the array (just like between consecutive slashes).

**To Reproduce**

```
console.log('/segment1/segment2/'.trim('/'));
```
=>
`/segment1/segment2/`

...which is to be expected, see API doc:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim

Also see this REPL which was created for related issue #415 :

https://repl.it/@danielweck/PreactWMRRouterTrimSlashes

**Expected behavior**

Expected result:

`segment1/segment2`

Suggested code correction:

`STR.replace(/^\//, '').replace(/\/$/, '')`

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - WMR Version: all

**Additional context**

**Comment by developit** [comment]
Ah! yikes. I wonder where else I've made that mistake haha.

FWIW I think we could shorten the suggestion to this:

```js
url.replace(/(^\/|\/$)/g, '')
```

... or this:

```js
url.split('/').filter(Boolean)
```
