### ISSUE TITLE
Preact devtools cause async lazy-loaded routes to crash ("Uncaught (in promise) Error: Missing Suspense")

### ISSUE THREAD

**Issue by danielweck** [preactjs/wmr#429]
**Describe the bug**

When `import 'preact/debug';` is added at the top of `index.js`, async / lazy components fail to display, the console shows the following error:
```
Uncaught (in promise) Error: Missing Suspense. The throwing component was: 
```

**To Reproduce**

1) `npm init wmr lazy-devtools`
2) `cd lazy-devtools`
3) open `public/index.js`, add `import 'preact/debug';` at the top of the file
4) `npm run start`
5) load `http://192.168.1.127:8080/about` in browser + open web inspector
6) alternatively, load `http://192.168.1.127:8080/` and navigate to `about`

**Expected behavior**

Async lazy-loaded routes do not crash

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - WMR Version: all

Reproduced on Firefox and Chrome with Preact devtools extension version `1.3.0`

**Additional context**

<img width="548" alt="Screenshot 2021-03-14 at 16 58 35" src="https://user-images.githubusercontent.com/625201/111077132-3f585f00-84e7-11eb-9558-8b54ce7dcba0.png">

**Comment by danielweck** [comment]
Reproduced on Firefox with Preact devtools extension version `1.3.0`

**Comment by danielweck** [comment]
Possibly related issues:
* https://github.com/preactjs/preact-devtools/issues/76
* https://github.com/preactjs/preact-devtools/issues/53
* https://github.com/preactjs/preact-devtools/issues/38

**Comment by marvinhagemeister** [comment]
Just tried it out again and can't reproduce that anymore 🎉 As far as I can tell from the git history, this was addressed with https://github.com/preactjs/wmr/pull/530
