### ISSUE TITLE
wmr build results in "Unterminated regular expression"

### ISSUE THREAD

**Issue by Snugug** [preactjs/wmr#434]
**Describe the bug**
When I run `wmr build`, I get "Unterminated regular expression". I have the following WMR configuration in `wmr.config.mjs`:

```js
import swPlugin from '@wmr-plugins/service-worker/sw-plugin.cjs';

export default function (options) {
  swPlugin(options);
}
```

WMR serving works as expected with no errors.

**Expected behavior**
The site to build

**Desktop (please complete the following information):**
 - OS: Mac OS 11.2.1
 - ZSH, Node v14.16.0
 - WMR Version 1.3.2

**Comment by danielweck** [comment]
Have you tried with `import swPlugin from '@wmr-plugins/service-worker';` instead of `import swPlugin from '@wmr-plugins/service-worker/sw-plugin.cjs';`?
(you are importing a CommonJS module inside a `*.mjs` ECMAScript module)
Documentation: https://github.com/preactjs/wmr/blob/main/packages/sw-plugin/README.md#usage

**Comment by Snugug** [comment]
I get an error when I do that:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'working-foldernode_modules/@wmr-plugins/service-worker/' imported from working-folderwmr.config.mjs
    at legacyMainResolve (internal/modules/esm/resolve.js:225:9)
    at packageResolve (internal/modules/esm/resolve.js:648:14)
    at moduleResolve (internal/modules/esm/resolve.js:696:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
Failed to load wmr.config.mjs
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'working-foldernode_modules/@wmr-plugins/service-worker/' imported from working-folderwmr.config.mjs
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received an instance of URL
```

**Comment by Snugug** [comment]
Figured out the issue: I was on 0.1.0 of the plugin which only includes the `.cjs` export, and NPM didn't for whatever reason update me to 0.1.1 when it came out which resolved this issue. Good to close.
