### ISSUE TITLE
Userland plugin doesn't work if it uses the the same file extension as a built-in plugin, with a different import prefix

### ISSUE THREAD

**Issue by danielweck** [preactjs/wmr#449]
UPDATE: the bugs still exist, but I now have found solutions to work around WMR's handling of core file extensions, such as SVG and JSON files. Here is a working `text:` plugin that does not require using alternative file extensions in order to avoid colliding with WMR's own handling (e.g. `*.jsonld` for JSON or `*.xml` for SVG):

```js
/** @type {import('wmr').Plugin} */
function textPlugin() {
    const IMPORT_PREFIX = 'text:';
    const INTERNAL_PREFIX = `\0${IMPORT_PREFIX}`;

    return {
        name: 'text-plugin',

        async resolveId(id, importer) {
            if (id[0] === '\0' || id[0] === '\b') return;

            if (id.startsWith(IMPORT_PREFIX)) {
                id = id.slice(IMPORT_PREFIX.length);
            } else return;

            // necessary for SVG file extension
            // (otherwise WMR's url: import prefix plugin creates an inline data: URL for the SVG asset)
            if (config.mode === 'start') {
                id = `${id}${'\0'}`;
            }

            // just in case the given importer has an import prefix
            if (importer) {
                importer = importer.replace(/^[\0\b]\w+:/g, '');
            }

            const resolved = await this.resolve(id, importer, { skipSelf: true });
            if (!resolved) {
                return;
            }

            // necessary for JSON file extension
            // (because WMR's json: import prefix plugin handles it by default)
            if (/^[\0\b]\w+:/g.test(resolved.id)) {
                resolved.id = resolved.id.replace(/^[\0\b]\w+:/g, '');
            }

            return `${INTERNAL_PREFIX}${resolved.id}`;
        },

        async load(id) {
            if (!id.startsWith(INTERNAL_PREFIX)) return;

            id = id.slice(INTERNAL_PREFIX.length);

            // necessary for SVG file extension
            // (otherwise WMR's url: import prefix plugin creates an inline data: URL for the SVG asset)
            if (config.mode === 'start') {
                id = id.replace(/\0$/, '');
            }

            id = path.resolve(config.cwd || '.', id);

            this.addWatchFile(id);

            const s = fs.readFileSync(id, { encoding: 'utf8' });

            return `export default \`${s}\``;
        },
    };
}
textPlugin.enforce = 'pre';
config.plugins.push(textPlugin());
```

**Describe the bug**

WMR's built-in plugins that handle specific file extensions (e.g. SVG in the "URL plugin") interfere with userland plugins that wish to handle the same file extensions under a different scheme (i.e. custom import prefix, e.g. `svg:` to include the raw SVG markup instead of creating an external image URL)

Culprit:

https://github.com/preactjs/wmr/blob/97eed9d79558fd8bd9baa1a4503a7bea781b7a5a/packages/wmr/src/plugins/url-plugin.js#L4

**To Reproduce**

`cake.svg`
=>
```svg
<!-- https://heroicons.com/ -->
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
<path
	stroke-linecap="round"
	stroke-linejoin="round"
	stroke-width="2"
	d="M21 15.546c-.523 0-1.046.151-1.5.454a2.704 2.704 0 01-3 0 2.704 2.704 0 00-3 0 2.704 2.704 0 01-3 0 2.704 2.704 0 00-3 0 2.704 2.704 0 01-3 0 2.701 2.701 0 00-1.5-.454M9 6v2m3-2v2m3-2v2M9 3h.01M12 3h.01M15 3h.01M21 21v-7a2 2 0 00-2-2H5a2 2 0 00-2 2v7h18zm-3-9v-2a2 2 0 00-2-2H8a2 2 0 00-2 2v2h12z"
/>
</svg>
```

1) `npm init wmr svg-import`
2) `cd svg-import`
3) open `public/pages/_404.js`, add at the top `import svgCakeUrl from './cake.svg'` (which is equivalent to `import svgCakeUrl from 'url:./cake.svg'`), and add in the JSX `<img src={svgCakeUrl} alt="" width={48} height={48} />`
4) `npm start` (or `npm run build --prerender && npm run serve`) => all works fine, but the image asset remains external, now we want to inline the SVG markup inside the JSX. Next step:
5) Add at the top `import svgCakeContent from 'svg:./cake.svg'`, and insert the following userland plugin in `wmr.config.mjs`:

UPDATE: scroll to the top of this thread to see the most up to date, working `text:` plugin.

```js
function svgPlugin() {
    const IMPORT_PREFIX = 'svg:';
    const INTERNAL_PREFIX = '\0svg:';
    const SVGEXT = '.svg';
    return {
        name: 'svg-plugin',
        async resolveId(id, importer) {
            if (id[0] === '\0' || id[0] === '\b') return;

            if (id.startsWith(IMPORT_PREFIX)) {
                id = id.slice(IMPORT_PREFIX.length);
            } else if (config.mode === 'build') {
                return;
            } else if (!id.endsWith(SVGEXT)) {
                return;
            }

            const resolved = await this.resolve(id, importer, { skipSelf: true });
            if (!resolved) return;

            resolved.id = `${INTERNAL_PREFIX}${resolved.id}`;
            return resolved.id;
        },
        async load(id) {
            if (!id.startsWith(INTERNAL_PREFIX)) return;

            id = id.slice(INTERNAL_PREFIX.length);

            id = path.resolve(config.cwd || '.', id);
            this.addWatchFile(id);

            const s = fs.readFileSync(id, { encoding: 'utf8' });
            console.log(j);

            return `export default \`${s}\``;
        },
        transform(code, id) {

            if (!id.endsWith(SVGEXT) || id.startsWith(INTERNAL_PREFIX)) return;

            return {
                code: `export default \`${code}\``,
                map: null,
            };
        },
    };
}
config.plugins.push(svgPlugin());
```

1) Now run `npm start` (or `npm run build --prerender && npm run serve`), and refresh the page => fail.
2) Copy the file `cake.svg` to `cake.svgx` (for example), change the extension accordingly in the above plugin (`const SVGEXT = '.svgx'`) and of course in the import as well (`import svgCakeContent from 'svg:./cake.svgx'`) => success.

I added a "trace" plugin to `console.log()` the `resolveId()` etc., and indeed there seems to be some interference due to the common SVG file extension. Related issue: https://github.com/preactjs/wmr/issues/446#issuecomment-802225547

**Expected behavior**

WMR's built-in plugins should allow userland plugins to define custom import prefixes for common file extensions.

**Desktop (please complete the following information):**

 - OS: all
 - Browser: all
 - WMR Version: all

**Additional context**

**Comment by danielweck** [comment]
As described above, my current workaround is to rename my SVG files with a file extension not handled internally by WMR (i.e. `.svgx`), but obviously this breaks useful features such as image viewers. 
If you have time to look into this plugin / file type handling problem, thank you :)

**Comment by danielweck** [comment]
By the way, and built-in `text:` import prefix plugin would be nice as a core WMR feature, don't you think? :)
That being said, I think it is more important that userland plugins can handle common file extensions without colliding with WMR's own internal file handling / import logic.

**Comment by marvinhagemeister** [comment]
Agree, it's something we need and want to change soon. Currently every plugin gets called with no respect to what they can work with. That relationship needs to be inverted so that plugins can subscribe to stuff they can deal with. The current `foo:` prefixes kinda act like a namespace or sort of import type and we should be able to have a way to skip calling a plugin when it can't deal with that.

Adding a `text:` import prefix is a great idea!

**Comment by danielweck** [comment]
I have now removed my ad-hoc JSON and SVG import prefix plugins, in favour of a generic TEXT plugin which imports the textual content of referenced resources (unlike WMR's URL plugin which preserves external files). In the JSON case, I just call `JSON.parse(jsonText)` if needed. In the SVG case, I use a wrapper component with `dangerouslySetInnerHTML={{ __html: svgText }}` in my JSX to inline small vector graphics (=> fewer HTTP requests).

Here's my working code (both `npm start` dev mode, and `npm run build --prerender && npm run serve` for production)

Typings:

```ts
declare module 'text:*' {
	const content: string;
	export default content;
}
```

Note the use of `.xml` extension so that I can view the file contents with XML formatting etc. (I cannot use `.svg` due to this issue #449)

```js
import svgText from 'text:./cake.xml';
```

`wmr.config.mjs`
=>
```
import path from 'path';

	function textPlugin() {
		const IMPORT_PREFIX = 'text:';
		const INTERNAL_PREFIX = `\0${IMPORT_PREFIX}`;

		return {
			name: 'text-plugin',

			async resolveId(id, importer) {
				if (id[0] === '\0' || id[0] === '\b') return;

				if (id.startsWith(IMPORT_PREFIX)) {
					id = id.slice(IMPORT_PREFIX.length);
				} else return;

				const resolved = await this.resolve(id, importer, { skipSelf: true });
				if (!resolved) return;

				return `${INTERNAL_PREFIX}${resolved.id}`;
			},

			async load(id) {
				if (!id.startsWith(INTERNAL_PREFIX)) return;

				id = id.slice(INTERNAL_PREFIX.length);

				id = path.resolve(config.cwd || '.', id);

				this.addWatchFile(id);

				const s = fs.readFileSync(id, { encoding: 'utf8' });

				return `export default \`${s}\``;
			},
		};
	}
	config.plugins.push(textPlugin());
```

**Comment by developit** [comment]
This seems like it would be addressed by `{ enforce: 'pre' }`, right?

**Comment by danielweck** [comment]
I'm afraid not. 
I am using WMR's latest build from the main branch.
If I change the `.xml` extension to `.svg` (I have both files in the containing folder):
```js
import svgCake from 'text:../svg/cake.xml';
```
...then the symptoms described above occur.
Here's my `text` plugin:
```js
	/** @type {import('wmr').Plugin} */
	function textPlugin() {
		const IMPORT_PREFIX = 'text:';
		const INTERNAL_PREFIX = `\0${IMPORT_PREFIX}`;

		return {
			name: 'text-plugin',

			async resolveId(id, importer) {
				if (id[0] === '\0' || id[0] === '\b') return;

				if (id.startsWith(IMPORT_PREFIX)) {
					id = id.slice(IMPORT_PREFIX.length);
				} else return;

				const resolved = await this.resolve(id, importer, { skipSelf: true });
				if (!resolved) return;

				return `${INTERNAL_PREFIX}${resolved.id}`; // \0TXT
			},

			async load(id) {
				if (!id.startsWith(INTERNAL_PREFIX)) return;

				id = id.slice(INTERNAL_PREFIX.length); // .replace(/\0TXT$/, '')

				id = path.resolve(config.cwd || '.', id);

				this.addWatchFile(id);

				const s = fs.readFileSync(id, { encoding: 'utf8' });

				return `export default \`${s}\``;
			},

			// transform(code, id) {
			// 	if (id.startsWith(INTERNAL_PREFIX)) return;

			// 	if (!id.endsWith('\0TXT')) return;
			// 	id = id.replace(/\0TXT$/, '');

			// 	return {
			// 		code: `export default \`${code}\``,
			// 		map: null,
			// 	};
			// },
		};
	}
	textPlugin.enforce = 'pre';
	config.plugins.push(textPlugin());
```

**Comment by danielweck** [comment]
PS: I was finding the `pre` + `normal` + `post` order confusing due to the differences between development vs. production plugin chains, so I now keep this comment in my WMR config file:

```js
	if (config.mode === 'start') {
		console.log('WMR START');

		// dev plugin order:
		// ------- PRE
		// externalUrlsPlugin
		// nodeBuiltinsPlugin
		// urlPlugin
		// jsonPlugin
		// bundlePlugin
		// aliasesPlugin
		// sucrasePlugin
		// processGlobalPlugin
		// sassPlugin
		// htmPlugin
		// wmrPlugin
		// fastCjsPlugin
		// resolveExtensionsPlugin
		// ------- NORMAL
		// ------- POST
	}
```
```js
	if (config.mode === 'build') {
		console.log('WMR BUILD');

		// prod plugin order:
		// ------- PRE
		// ------- NORMAL
		// nodeBuiltinsPlugin
		// externalUrlsPlugin
		// sucrasePlugin
		// htmlEntriesPlugin
		// publicPathPlugin
		// aliasesPlugin
		// htmPlugin
		// sassPlugin
		// wmrStylesPlugin
		// wmrPlugin
		// processGlobalPlugin
		// resolveExtensionsPlugin
		// fastCjsPlugin
		// npmPlugin
		// urlPlugin
		// jsonPlugin
		// ------- POST
		// bundlePlugin
		// optimizeGraphPlugin
		// minifyCssPlugin
		// copyAssetsPlugin
	}
```

**Comment by danielweck** [comment]
> I'm afraid not.

Ah wait, this works in prerender production builds (`npm run build --prerender && npm run serve`), but not in development `npm start` mode.

**Comment by developit** [comment]
@danielweck sidebar - what's the reason for overriding the `text:` plugin? Is there something we need to fix in the built-in one?

**Comment by danielweck** [comment]
> @danielweck sidebar - what's the reason for overriding the `text:` plugin? Is there something we need to fix in the built-in one?

Is there a built-in `text:` plugin?  :)
(sorry if I've missed it!)

https://github.com/preactjs/wmr/tree/main/packages

https://github.com/preactjs/wmr/tree/main/packages/wmr/src/plugins

But, irrespective of that, the bug report here is about userland plugins that handle an already-handled file extension => breakage, some sort of infinite dance between `resolveId` and `load` (as described).

**Comment by gryzzly** [comment]
heya, do I understand correctly that this bug is the reason for json imports breaking build?

I have `import content from './content.json'` in `index.js`, it works in development, but causes 
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```
when trying to run build.

If not I’m happy to report this separately.

**Comment by marvinhagemeister** [comment]
My goal is that plugins (including internal ones) share the same order in prod and dev. It's the thing I'll likely tackle next.

**Comment by danielweck** [comment]
> My goal is that plugins (including internal ones) share the same order in prod and dev.

I am keeping an eye on your commits, and I will update my notes + tests once the main branch stabilises :)

https://github.com/preactjs/wmr/issues/449#issuecomment-808466358

**Comment by danielweck** [comment]
I see that there is an upcoming PR with further changes to the plugin system, so I look forward to testing this :)
https://github.com/preactjs/wmr/pull/479

(I stopped using the official WMR release and I now build my app directly with WMR's `main` branch)

Seems another dev is experiencing issues with JSON import: https://github.com/preactjs/wmr/discussions/474

**Comment by danielweck** [comment]
> My goal is that plugins (including internal ones) share the same order in prod and dev.

Well done for cutting a new release! 👍 
(which I am now using instead of a self-build from the `main` branch)

I updated my post in this thread about the ordered list of plugins: https://github.com/preactjs/wmr/issues/449#issuecomment-808466358

**Comment by danielweck** [comment]
Following this recent bugfix https://github.com/preactjs/wmr/pull/491 I decided to run tests again.

I found a workaround for SVG files (which means I can now stop using the XML file extension), but I couldn't find a working solution for JSON files (so I continue to use the JSONLD extension instead).

My workaround is to append `\0` to the file path (aka `resolve` `id`) so that the file extension fail to match in WMR's built in plugins (for SVG, that's the URL plugin). My `pre` plugin then removes the appended `\0` suffix in the `load` phase. Here is my updated `text` plugin:

(note that I apply this special treatment with `if (config.mode === 'start')` as production builds do not need it, somehow)

```js

	/** @type {import('wmr').Plugin} */
	function textPlugin() {
		const IMPORT_PREFIX = 'text:';
		const INTERNAL_PREFIX = `\0${IMPORT_PREFIX}`;

		return {
			name: 'text-plugin',

			async resolveId(id, importer) {
				if (id[0] === '\0' || id[0] === '\b') return;

				if (id.startsWith(IMPORT_PREFIX)) {
					id = id.slice(IMPORT_PREFIX.length);
				} else return;

				if (config.mode === 'start') {
					id = `${id}${'\0'}`;
				}

				const resolved = await this.resolve(id, importer, { skipSelf: true });
				if (!resolved) return;

				return `${INTERNAL_PREFIX}${resolved.id}`;
			},

			async load(id) {
				if (!id.startsWith(INTERNAL_PREFIX)) return;

				id = id.slice(INTERNAL_PREFIX.length);

				if (config.mode === 'start') {
					id = id.replace(/\0$/, '');
				}

				id = path.resolve(config.cwd || '.', id);

				this.addWatchFile(id);

				const s = fs.readFileSync(id, { encoding: 'utf8' });

				return `export default \`${s}\``;
			},
		};
	}
	textPlugin.enforce = 'pre';
	config.plugins.push(textPlugin());
```

**Comment by danielweck** [comment]
Ah, great! I found a trick to work around the JSON file extension (i.e. to bypass WMR's core `json:` import prefix handler):

After the `this.resolve()` call in my `text:` plugin I now "sanitize" the returned `resolve.id`, ensuring no other import prefix was somewhat injected by WMR's core plugin chain:

```js
if (/^[\0\b]\w+:/g.test(resolved.id)) {
    resolved.id = resolved.id.replace(/^[\0\b]\w+:/g, '');
}
```

I'll update my `text:` plugin code snippet accordingly, in previous comments in this thread.

PS: just in case the `importer` itself carries an import prefix, I also sanitize it before calling `this.resolve(id, importer, { skipSelf: true })`:

```js
if (importer) {
    importer = importer.replace(/^[\0\b]\w+:/g, '');
}
```

**Comment by marvinhagemeister** [comment]
I've spend yesteday evening looking into this and I feel like there is a missing piece in our resollution handling. Here my current thoughts on this.

Conceptually, our builtin json plugin should only transform json files into a module and resolve without the `json:` prefix if it was found.

Currently most plugins (even ones for rollup or vite) kinda misuse `resolveId` to take ownership of a path by slapping `\0` in front of it. This breaks recursive resolution when more than one prefixes are involved.

```txt
my-json:json:./foo/bar.json -> \0my-json:\0json:./foo/bar.json
```

Vite was forced to go that route because plugins are added _after_ builtin ones by default. Since we put them just before builtins by default we don't share the same fate. So any plugins that deals with prefixes should just keep them as is:

```js
{
  name: 'my-plugin',
  async resolveId(id, importer) {
    if (!id.startsWith('my-json:')) return;

    id = id.slice(IMPORT_PREFIX.length);
    const resolved = await this.resolve(id, importer, { skipSelf: true });
    return resolved && 'my-json:' + resolved.id;
  },
  // ...
}
```

The realisation here is that prefixes (similar to webpack loader queries btw) are recursive in nature. By making that a first class citizen we can avoid plugins needing to add `\0` in front of every path. 

Since by rollup has no knowledge of these semantics we should add a default plugin to the end that has a `load()` hook where it strips all prefixes and loads the file. This allows us to put security checks to prevent directory traversal attacks at a single place. Things like "don't load stuff outside of the current cwd". Custom plugins would only need to add a custom `load()` hook if they really want to change loading semantics, not just transformation stuff. That belongs into `transform()` and I feel our builtin json plugin is wrong to misuse `load()` here.

Something that's not clear to me though is how we should deal with recursive `transform()` calls in such a scenario. If we take the above example of `my-json:json:./foo/bar.json` we'd be still lacking a way to skip the builtin one. Because in theory we'd need to call each prefix for things like `css:less:./foo.css`.

**Comment by danielweck** [comment]
Yes, "nested" import prefixes have been problematic in my WMR project.

Case in point:

The first `enforce=pre` plugin in my WMR config is one that allows me to code using "absolute" import paths (i.e. relative to the `public` folder in my case) in order to avoid using long relative paths from deep-nested TS/JS files (e.g. `import { foo } from '../../../bar.js';`).

Side note - I use the following TypeScript aliases in my `tsconfig.json` in order to support the syntax `~/PATH/TO/STUFF` in Visual Studio Code (e.g. click-to-navigate):

```json
		"baseUrl": ".",
		"paths": {
			"~/*": ["./public/*"],
		}
```

Here's the plugin:

```js
	/** @type {import('wmr').Plugin} */
	function rootPlugin() {
		return {
			name: 'root-plugin',
			async resolveId(id, _importer) {
				if (!id.startsWith('~/')) return;
				const absolute = path.join(config.cwd, id.substring(2)).replace(/\\/g, '/');
				console.log('root-plugin', absolute);
				return this.resolve(absolute);
			},
		};
	}
	rootPlugin.enforce = 'pre';
	config.plugins.push(rootPlugin());
```

This works perfectly fine in combination with my `text:` plugin, both with the development server (`npm start`) and the production `dist` (`npm run build --prerender && npm run serve`). For example:

```js
import svgCake from 'text:~/vectors/cake.svg';
import jsonTest from 'text:~/data/test.json';

// from here I can inline / use the textual contents of the JSON and SVG files
```

...unfortunately, this breaks completely with WMR's built-in `json:` and `url:` plugins, when using the import prefixes **explicitly**. For example, this works fine:

```js
import jsonUrl from '~/path/to/test.json';
import imgUrl from '~/path/to/img.png';

import jsonObj from '~/path/to/test.json';
```

...but this breaks:

```js
import jsonUrl from 'url:~/path/to/test.json';
import imgUrl from 'url:~/path/to/img.png';

import jsonObj from 'json:~/path/to/test.json';
```

Good luck tackling this architectural problem, as it seems quite tricky 👍 

In the meantime, I am documenting WMR's caveats in my codebase in order to avoid the current pitfalls, and luckily I now have all the workarounds I need to focus on implementing the business logic without having to think too much about WMR's underlying mechanics :)
(though I will be happy to continue run tests and report back here, if it helps)

Thanks a lot for all your hard work!

**Comment by danielweck** [comment]
Follow-up issue: https://github.com/preactjs/wmr/issues/524
