### ISSUE TITLE
Move `process.env` to `import.meta.env`

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/wmr#457]
**Is your feature request related to a problem? Please describe.**

Move `process.env` to `import.meta.env`. It's more in line with the spirit of ES Modules and doesn't rely on us shimming a global variable.

**Describe the solution you'd like**
Store environment vars at `import.meta.env`. We'll probably need to keep transpiling `process.env` for a good while though as it's everywhere in the React ecosysstem.

**Describe alternatives you've considered**
-

**Additional context**

Both snowpack and vite store env variables at `import.meta.env`

**Comment by developit** [comment]
This is a fantastic idea.

**Comment by piotr-cz** [comment]
I think react ecosystem will eventually drop using `process.env`, as it's not provided by webpack 5 anymore (see webpack > [To v5 from v4](https://webpack.js.org/migrate/5/#run-a-single-build-and-follow-advises)):

> process is not defined.
> webpack 5 does no longer include a polyfill for this Node.js variable. Avoid using it in the frontend code.

For now it should be possible to replace it:

```js
import rollupPluginReplace from '@rollup/plugin-replace'

export default function (config) {
  config.plugins.push(
    rollupPluginReplace({
      'process.env': 'import.meta.env'
    })
  }
}
```
