### ISSUE TITLE
`npm install` is not run and node_modules folder is not created on project creation

### ISSUE THREAD

**Issue by gryzzly** [preactjs/wmr#462]
**Describe the bug**
When following the steps described in README and using `npm init` dependencies aren’t installed.

**To Reproduce**

```
npm init wmr your-project-name
```
and then attempting to start the project
`cd your-project-name && npm run start` 

one is presented with missing package error:
```
┌ [12:33:24] ~/Source/your-project-name
└ npm run start

> @ start /Users/foo/Source/your-project-name
> wmr

sh: wmr: command not found
```

**Expected behavior**
Either suggestion to run `npm install` in the initialized project in README or instsalled dependencies after initializing the project.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser  - 
 - WMR Version [e.g. 22] 1.3.2

**Comment by developit** [comment]
Hi @gryzzly - this is a bug, `npm install` is supposed to run automatically. Can you provide the versions of npm and Node you're using?

`npm -v; node -v`

**Comment by gryzzly** [comment]
hey hey,

```
┌ [12:45:23] ~/Source/your-project-name
└ npm -v; node -v
6.14.10
v14.15.4
```

**Comment by marvinhagemeister** [comment]
Just tried the steps listed in the issue description and I'm unable to reproduce it, even with the same node + npm version. The `wmr` command is available and the server boots up as expected 👍
