### ISSUE TITLE
CSS @import not transformed

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/wmr#481]
**Describe the bug**

@ForsakenHarmony mentioned in Slack files imported via the `@import` statement in CSS are bot transformed. Add a test case for this and verify that they work

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - WMR Version [e.g. 22]

**Additional context**

**Comment by rschristian** [comment]
I believe this is the same thing as outlined in #254?

**Comment by ForsakenHarmony** [comment]
Yes, sounds like it

**Comment by ettoredn** [comment]
I too am experiencing this problem. The SCSS file linked from index.html does not get compiled by SASS. I tried using a simple `@at-root ... {}` rule, and the rule is kept as it is in the output.

**Comment by rschristian** [comment]
@ettoredn Are you sure you're not getting a correctly built CSS file in addition to your raw SCSS file? #361 mentions this happening. Is your experience different?

Regardless, I don't think this is the same issue as you're seeing. From your description, it sounds like you're having more of an issue with SASS, not anything to do with the way `@import`s in CSS are (not) transformed as the files move around into `dist/`.

It would be great if you could create a new issue for that.

**Comment by marvinhagemeister** [comment]
I can't reproduce that anymore in `main`. It's presumably resolved with #684 and #685 .
