### ISSUE TITLE
preact-iso router always intercepts same-origin link clicks, not possible to opt-out

### ISSUE THREAD

**Issue by danielweck** [preactjs/wmr#488]
To reproduce, add "local" (same origin) links to any WMR demo page, e.g.:

```html
<a href="/file.svg">
link to file
</a>

<a href="/file.svg" rel="noreferrer noopener" target="_BLANK">
link to file (target BLANK)
</a>
```

As you can see, I serve static resources on the same domain, which I do not want the router to intercept.

=> the router attempts to load the referenced resources, and fails.

My current workaround is to instantiate my own higher-precedence link handler, and to author the above links with an additional attribute (`data-wmr-skip-router`):

```html
<a href="/file.svg" data-wmr-skip-router>
link to file
</a>

<a href="/file.svg" rel="noreferrer noopener" target="_BLANK" data-wmr-skip-router>
link to file (target BLANK)
</a>
```

Here's the mount / unmount logic in my root Preact app component:

```js
useEffect(() => {
    const clickHandler = (ev) => {
        if (!ev.target) {
            return;
        }
        const linkEl = ev.target.closest('a[href]');
        if (!linkEl) {
            return;
        }

        if (linkEl.origin !== window.location.origin) {
            return;
        }

        if (ev.target.getAttribute('data-wmr-skip-router')) {

            ev.stopPropagation(); // prevents preact-iso router
            ev.preventDefault(); // prevents default linking / popup menu behaviour

            if (ev.target.getAttribute('target') === '_BLANK') {
                window.open(linkEl.href, '_blank');
            } else {
                window.location.href = linkEl.href;
            }

            return;
        }
    };

    document.addEventListener('click', clickHandler, {
        capture: true,
    });

    return () => {
        document.removeEventListener('click', clickHandler, {
            capture: true,
        });
    };
}, []);
```

`preact-router` implements some filtering logic:

https://github.com/preactjs/preact-router/blob/5fb140e65241bdc42e06b7b7f0d66ff85af9a34e/src/index.js#L84-L85

```js
	// ignore links with targets and non-path URLs
	if (!href || !href.match(/^\//g) || (target && !target.match(/^_?self$/i))) return;
```

https://github.com/preactjs/preact-router/blob/5fb140e65241bdc42e06b7b7f0d66ff85af9a34e/src/index.js#L116

```js
if (t.hasAttribute('native')) return;
```

`preact-iso/router` only filters by origin match:

https://github.com/preactjs/wmr/blob/34b0ddb97ae7dce0bf907b86176cb9fc6ac947cd/packages/preact-iso/router.js#L8

**Comment by developit** [comment]
I think we could go with the `target` check here, it's pretty straightforward.
