### ISSUE TITLE
npm init wmr fails

### ISSUE THREAD

**Issue by zgoda** [preactjs/wmr#506]
**Describe the bug**

`npm init wmr projectname` fails with error "Cannot find module string_decoder/"

**To Reproduce**
1. run `npm init wmr myprojectname` in terminal

**Expected behavior**

Project structure gets initialised.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: n/a
 - WMR Version n/a

**Additional context**

```console
$ npm init wmr dashboard-preact-typescript
Need to install the following packages:
  create-wmr
Ok to proceed? (y) y
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'string_decoder/'
Require stack:
- /home/jazg/.npm/_npx/3c66316f091b0520/node_modules/create-wmr/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/jazg/.npm/_npx/3c66316f091b0520/node_modules/create-wmr/dist/index.js:2:194)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/jazg/.npm/_npx/3c66316f091b0520/node_modules/create-wmr/dist/index.js'
  ]
}
npm ERR! code 1
npm ERR! path /home/jazg/work/learn
npm ERR! command failed
npm ERR! command sh -c create-wmr "dashboard-preact-typescript"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jazg/.npm/_logs/2021-03-30T17_10_10_352Z-debug.log
```

[2021-03-30T17_10_10_352Z-debug.log](https://github.com/preactjs/wmr/files/6230910/2021-03-30T17_10_10_352Z-debug.log)

**Comment by developit** [comment]
@zgoda which Node version are you using?

**Comment by developit** [comment]
This is the same issue as #371, which was determined to be a build/publishing error.

**Comment by developit** [comment]
If you could try with the previous version that would help us (along with the above info):

`npm init wmr@0.3.0 projectname`

**Comment by developit** [comment]
This should fix itself if you run:

```sh
npm init wmr projectname --prefer-online
```

**Comment by zgoda** [comment]
In npm log:

```
34 http fetch GET 304 https://registry.npmjs.org/create-wmr 143ms (from cache)
35 silly placeDep ROOT create-wmr@0.1.4 KEEP for:  want: ^0.1.4
```

So it does not.

Force-cleared npm cache, same result.

**Comment by rschristian** [comment]
Sorry to repeat, but have you ever used the yarn initializer, i.e., `yarn create wmr foobar`? 

`yarn create` unfortunately does install the module globally, for both npm & yarn. While Yarn knows how to handle this, I believe `npx`/`npm init` will use that global install. As it's not cached, but installed, forcing a stale check won't have any effect.

**Comment by zgoda** [comment]
I've never used yarn with wmr. I guess I've never used `create` feature.

```console
$ yarn global list
yarn global v1.22.10
Done in 0.03s.
```

**Comment by rschristian** [comment]
That's good. I guess the other item to check would be npm. `npm list -g --depth 0` will list out any globals you have installed. Hopefully wmr isn't in that list.

**Comment by zgoda** [comment]
Also not there:

```console
$ npm ls -g --depth 0
/home/jazg/.nvm/versions/node/v14.16.0/lib
├── npm@7.7.6
└── yarn@1.22.10
```

**Comment by zgoda** [comment]
I suppose this is local - tried the same combo (OS, Node, npm versions) on fresh VM and it works without a glitch so feel free to close.
