### ISSUE TITLE
npm start fails (wmr v1.5.0)

### ISSUE THREAD

**Issue by piotr-cz** [preactjs/wmr#510]
**Describe the bug**

Running `wmr` v1.5.0 with yarn/ npm throws an error `Error: Cannot find module 'rollup-plugin-visualizer'`

**To Reproduce**

1.  ```console
    git clone https://github.com/preactjs/wmr
    cd wmr/docs
    yarn install
    yarn start
    ```
4. See `Error: Cannot find module 'rollup-plugin-visualizer'`

**Expected behavior**
no error.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: CLI
- Node Version: 14.15.0
- WMR Version: 1.5.0

**Additional context**
Related PR: https://github.com/preactjs/wmr/pull/508

**Comment by developit** [comment]
Ah darn - I can take a look at this, seems like we are missing a piece of the bundle.

**Comment by piotr-cz** [comment]
This worked for wmr repo:

```console
$ docs
cd ..
yarn install
cd docs
yarn install
yarn start
```

However it doesn't when I use wmr in my project

**Comment by piotr-cz** [comment]
Thanks #489 fixed the issue 👍
