### ISSUE TITLE
Blank page on syntax error after reload

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/wmr#521]
**Describe the bug**
When the user has a syntax error in a script file and reloads the page, it will be blank. The console prints the usual import error in that case. Any file changes from then on won't trigger a reload of the browser tab.

This is caused by syntax errors blocking the runtime from being loaded in the first place. To work around that we should inject the runtime into the HTML.

**To Reproduce**

1. Open demo app `yarn demo start`
2. Create a syntax error in one of the `.js` files
3. Reload the browser window
4. Fix the error from 2.

**Expected behavior**
Browser should show reload and show the page again

**Desktop (please complete the following information):**

- OS: [e.g. MacOS 11.2.3, Windows 10]
- Browser: [e.g. chrome, safari]
- Node Version: [e.g. 15.8]
- WMR Version: [e.g. 1.3.1]

**Additional context**

**Comment by developit** [comment]
I think fixing #294 would fix this.
