### ISSUE TITLE
in docs Slot lib, `initial` is set to true instead of false

### ISSUE THREAD

**Issue by danielweck** [preactjs/wmr#539]
I think this is a coding typo:

https://github.com/preactjs/wmr/blob/8d5d1d82d98c7f2e2eaccb92ff6890cf1e2e6139/docs/public/lib/slots.js#L45-L48

**Comment by danielweck** [comment]
By the way, shouldn't `initial` be a `useRef()` here?

**Comment by developit** [comment]
Hah! Yes - correct on both accounts. I think the simple variable was from before I added support for swapping `name`.
