### ISSUE TITLE
in docs Slot lib's pub/sub, should unsubscribe on unmount (layout effect cleanup)

### ISSUE THREAD

**Issue by danielweck** [preactjs/wmr#540]
Current code:

https://github.com/preactjs/wmr/blob/8d5d1d82d98c7f2e2eaccb92ff6890cf1e2e6139/docs/public/lib/slots.js#L34

...with pub/sub unsubscribtion on unmount cleanup:

```js
useLayoutEffect(() => {
    const unsub = sub(name, update);
    return () => unsub;
}, [name]);
```

**Comment by JoviDeCroock** [comment]
PR's are welcome 😄

**Comment by danielweck** [comment]
oh I am so sorry, of course! (brain fart)
sorry for wasting your time, I will be more careful next time.
