### ISSUE TITLE
Unable to import react-countdown

### ISSUE THREAD

**Issue by Afsoon** [preactjs/wmr#545]
**Describe the bug**
Unable to import [React Countdown](https://github.com/ndresx/react-countdown), I notice that the original source code mix PropTypes with TS and is a React Class component. 

**To Reproduce**

1. Create a project from zero
2. Install the `react-countdown` library.
3. Create a basic component, as the following:
```typescript
import Countdown, { CountdownRenderProps } from 'react-countdown';

function timerRenderer ({ completed, seconds, minutes  }: CountdownRenderProps){
 if (completed) {
  return <span>00:00</span>;
 } else {
  return <span>{minutes}:{seconds}</span>;
 }
}

export default function Timers() {
  return <Countdown date={Date.now() + 70000} renderer={timerRenderer} />
}

```

4. The dev tools display the following error:
![imagen](https://user-images.githubusercontent.com/713534/115857245-bdd0e680-a42d-11eb-8612-77c55432bdf6.png)
5. The compiled code is the following:
![imagen](https://user-images.githubusercontent.com/713534/115858103-d55c9f00-a42e-11eb-9ec1-7972722a8cad.png)

**Expected behavior**
Be able to import react-countdown component. 

**Desktop (please complete the following information):**

- OS: OS X 10.15.17
- Browser: Firefox 87.0
- Node Version: 14.8.0
- WMR Version: 1.2.0

**Comment by JoviDeCroock** [comment]
The issue here seems to relate to a similar one as we're faced with when importing `react` itself, [prop-types](https://www.runpkg.com/?prop-types@15.7.2/index.js) only exports CJS/UMD and has no ESM build.

**Comment by developit** [comment]
(see #168  / #109)

**Comment by Afsoon** [comment]
Thank you for you fast response, so I will use `preact-cli`, I test it and works, until this is solve. Keep going with the job!
