### ISSUE TITLE
With WMR 2.0.0: duplicate `<script type="isodata"></script>` in prerendered HTML, due to `preact-iso` package not updated (currently `2.0.0`)

### ISSUE THREAD

**Issue by danielweck** [preactjs/wmr#592]
WMR 2.0.0 release notes:

https://github.com/preactjs/wmr/releases/tag/wmr%402.0.0

> Support injecting prerender data by returning a data key from the prerender function

https://github.com/preactjs/wmr/pull/585/files#diff-56e786dcb60ae19cef15ade284bd414d8a37f0c6534cee82bca47498797428dd

...but `preact-iso` is currently `2.0.0` which ships with:

https://github.com/preactjs/wmr/blob/6b25180b870aab137bb29f7f9cc8295d9f0067c3/packages/preact-iso/prerender.js#L49-L51

instead of:

https://github.com/preactjs/wmr/blob/00ed4e1d428177b77fe5b98abc1e48ed739cb3e0/packages/preact-iso/prerender.js#L49-L50

See published NPM package:

https://unpkg.com/browse/preact-iso@2.0.0/prerender.js

Consequence: `<script type="isodata"></script>` is generated alongside `<script type="isodata">{"foo":"bar"}</script>` when `prerender()` returns `{ data: { foo: 'bar' } }` instead of `{ data: undefined }`

Solution: publish `preact-iso` v-next :)

**Comment by developit** [comment]
lol - @danielweck we're just discussing this in Slack, it's not yet decided whether `isodata` will be produced by `wmr` or `preact-iso`.

**Comment by danielweck** [comment]
My local fix is to build the entire WMR project myself from the `main` branch (`yarn && yarn ci`), and to copy the generated packages from here into my project (overriding `node_modules/wmr` etc.).

**Comment by danielweck** [comment]
> also only injects the script tag when a `.data` object is returned from prerender(), which causes `hydrate()` to pick the wrong root element (it uses the parent of the script tag).

Yes indeed, I immediately noticed this regression and was going to file a separate bug. I'll leave it to you then :)

**Comment by JoviDeCroock** [comment]
This is fixed in latest https://www.runpkg.com/?preact-iso@2.0.3/prerender.js#49
