### ISSUE TITLE
After the build, line breaks are transformed into nothing

### ISSUE THREAD

**Issue by jt3k** [preactjs/wmr#621]
**Bug description**
build command removes line breaks and spaces in text

**To Reproduce**

1. install wmr via `npm init wmr your-project-name` command
2. `cd your-project-name && npm i`
3. edit `your-project-name/public/pages/home/index.js` file
add a line break to this line
before: 
```jsx
<p>This is the home page.</p>
```
after:
```jsx
<p>This is the
home page.</p>
```
4. build and serve `npm run build & npm run serve`
5. we now have the text `This is thehome page.` on the page

**Expected behavior**
site display the text `This is the home page.`

**Desktop (please complete the following information):**

- OS: MacOS 11.3.1
- Browser: all
- Node Version: v14.17.0
- WMR Version: wmr@2.0.2

**Additional context**
the bug is not present in development mode (`npm start`)

**Comment by marvinhagemeister** [comment]
@jt3k Thanks for reporting this! Just published a new version with the fix: https://github.com/preactjs/wmr/releases/tag/wmr%402.1.0

**Comment by jt3k** [comment]
thanks, fixed blazing fast!
