### ISSUE TITLE
Add @import path resolution for sass

### ISSUE THREAD

**Issue by Inviz** [preactjs/wmr#642]
**Is your feature request related to a problem? Please describe.**
Currently `sass` ignores aliases. That creates desparity with js files.

**Describe the solution you'd like**
At least node-sass has `importer` feature for that, to rewrite paths. Not sure abourt dart-sass
https://github.com/sass/node-sass#importer--v200---experimental

**Describe alternatives you've considered**
We could do the hack of rewriting raw @import declarations, that would work for all sass implementations

**Comment by marvinhagemeister** [comment]
Had a go at this, but it seems like sass' `importer` feature doesn't work. Neither passing the file path or file contents do anything. It just silently ignores that import for me.

**Comment by ettoredn** [comment]
Except that it has nothing to do with sass, but all to do with WMR.

**Comment by Inviz** [comment]
Super excited about this! Go Marvin!!
