### ISSUE TITLE
Fresh wmr project created with create-wmr failed to build. 

### ISSUE THREAD

**Issue by mjeffryes** [preactjs/wmr#647]
**Describe the bug**
I walked through the quick start but was unable to build the resulting project. Not sure if this is specific to my machine somehow, but thought I'd better report it in case I'm not the only one.

**To Reproduce**
```
$ npm init wmr foo
$ cd foo
$ npm run build

> @ build /Volumes/Data/workspace/source/foo
> wmr build --prerender

Error: Not supported
    at eval (eval at q$e (/Volumes/Data/workspace/source/foo/node_modules/wmr/wmr.cjs:2:2528201), <anonymous>:1:7)
    at q$e (/Volumes/Data/workspace/source/foo/node_modules/wmr/wmr.cjs:2:2528208)
    at async Y$e (/Volumes/Data/workspace/source/foo/node_modules/wmr/wmr.cjs:2:2529938)

Error: Failed to load wmr.config.mjs
Error: Not supported
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object

    at q$e (/Volumes/Data/workspace/source/foo/node_modules/wmr/wmr.cjs:2:2528350)
```

**Expected behavior**
Should build the example project.

**Desktop (please complete the following information):**

- OS: Mac OS X 10.15.7
- Node Version: v12.14.1
- WMR Version: 2.2.0

**Comment by developit** [comment]
I believe this may be an issue with ESM on Node 12.14. Can you try deleting the `wmr.config.mjs` to see if it completes as expected?

**Comment by rschristian** [comment]
Probably worth noting that we do have the `"engines"` field specifying Node >= 12.17 being acceptable. Updating to at least that point would likely be a good idea to ensure you're in supported & tested territory

https://github.com/preactjs/wmr/blob/522b124a691e57ca084adc901e7ba42498aeba8f/packages/wmr/package.json#L161-L163

**Comment by mjeffryes** [comment]
deleting `wmr.config.mjs` allows it to progress a little further:
```
$ npm run build

> @ build /Volumes/Data/workspace/source/foo
> wmr build --prerender


Wrote 23Kb to disk:
  dist/index.html 469b
  dist/index.587dac27.js 17Kb
  dist/assets/style.e6ee4bcf.css 499b
  dist/chunks/index.c9e2ea4c.js 214b
  dist/chunks/prerender.37a94b4d.js 4.8Kb

Error: Not supported

    at eval (eval at T$e ([worker eval]:1:860), <anonymous>:3:1)
    at T$e ([worker eval]:1:906)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `wmr build --prerender`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mjeffryes/.npm/_logs/2021-05-27T03_04_35_527Z-debug.log
```

I'll see if updating node to 12.17 fixes it

**Comment by mjeffryes** [comment]
builds successfully on node v12.17.0
