### ISSUE TITLE
How do I add a testing framework?

### ISSUE THREAD

**Issue by freund17** [preactjs/wmr#679]
I'd like to integrate with a testing framework and was wondering how to do that.
Specifically, I had karma + jasmine in mind, but I'm open to other suggestions as well.

My hope is to achieve the following:

- I want to write *.spec.ts(x)-files, which serve as entry points to my tests.
- My tests should run in the same environment as my application later would. (aka. a modern browser\*)
- I should be able to `import` everything like in my normal production code (including custom plugins, css modules, etc.)
- I should not have to maintain multiple sets of the same configuration for different build tools.
- Only recompile/rerun tests related to changed files while in "watch mode".
- Support for code coverage (BONUS: using V8, instead of instrumentation)
- VS Code integration (displaying and updating test results and coverage)

I know, this isn't strictly WMR-related, but I thought this would be the place to ask for help in establishing a modern, fast workflow. 😊 
But maybe WMR was only ever intended for rapid prototyping and I'm completely wrong here. 🙈 

Anyways, from my limited knowledge I'd guess I could get most of the way where I want to be using Karma + Jasmine + `karma-rollup-preprocessor` + access to the [`getPlugins`](https://github.com/preactjs/wmr/blob/81529987c3aeafcd99925e1edd9fab5b33a60f94/packages/wmr/src/lib/plugins.js#L29) function...

But what do you think?
Is my idea to naive?
Do you already have a setup like this and what tools did you use?
What points on my list do you think are the hardest to achieve and why?

\* I like `jsdom` as much as the next guy, but there are some APIs that just aren't supported and while I could mock my way around those, this makes testing more cumbersome - especially for those colleges, that are just transitioning over from a java codebase and do not jet understand the entire ecosystem and the differences between browser, Node.js, jsdom, etc...

**Comment by marvinhagemeister** [comment]
Basing a testing framework on top of WMR is an interesting pitch and something we'd love to see in the future. That said this question is _very_ broad so it's impossible to give a concrete answer or concrete steps on how to reach that goal. From my knowledge of karma I don't think marrying karma with WMR is going to be fruitful as they have quite different architectures. Instead it sounds easier to just add the few rollup plugins you need and off you go. The plugins in WMR are mostly there to deal with WMRs specific dev mode.
