### ISSUE TITLE
Console warning: A preload for 'xyz.js' is found, but is not used because the script type does not match.

### ISSUE THREAD

**Issue by nikoudel** [preactjs/wmr#682]
After creating a new project with `npm init wmr your-project-name` and starting the server with `npm start` or `npm run serve` I'm getting these console warnings (on Chrome and Firefox):

```
A preload for 'http://localhost:8080/index.24f43138.js' is found, but is not used because the script type does not match.

The resource http://localhost:8080/index.24f43138.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

Is that OK?

**Comment by developit** [comment]
Hiya! It looks like we need to update the default template: the link should have `rel="modulepreload"`:

https://github.com/preactjs/wmr/pull/683/files#diff-a8cda128cb94abbf05da95f536a9a0f21865f1229547c84fff7be9764b24268bR9

(you can make this change in your own `index.html` to fix the warning.

**Comment by nikoudel** [comment]
It worked, thanks!
