### ISSUE TITLE
Improve source map handling

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/wmr#699]
The source map handling in WMR can be a lot better. Namely:

- [x] Ensure `--sourcemap` generates sourcemaps #715 
- [x] Merge source maps in `container.transform()`
- [x] Ensure `acorn-traverse` generates correct mappings
- [x] Always include `sourcesContent`, so that the original code is shown in browser devtools
- [ ] ~~Ensure npm plugin supports source maps (might need a rewrite)~~ - out of scope for now. The rewrite will happen either way and we can do the source maps in one go
- [x] Add source map support to `.sass` (iirc they have different file mappings)
- [x] Decide on path format `./foo.js` vs `foo.js`
- [x] Improve performance of source map generation (check if it can be made so fast, that we can turn this always on)

**Comment by Inviz** [comment]
Huge plus one on this. Currently debugging things in builds is a pretty sizable PITA. On my app, chrome code formatted just gives up, and Sentry error reports also are pretty damn useless.

**Comment by Inviz** [comment]
In my app what i'm seeing is that .js file has a sourcemap file that goes like this:
```
{"version":3,"file":"index.31a59432.js","sources":["source:///components/formField/style.module.scss","source:///components/combobox/style.module.scss","source:///components/form/style.module.scss","source:///components/button/style.module.scss"....
```

The issue is that sources array only has scss files, and no javascript files at all.

**Comment by Inviz** [comment]
And there's these messages as well:
``` Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (default-loaders) was used to transform files, but didn't generate a sourcemap for the transformation.```

**Comment by Inviz** [comment]
If defaultLoaders plugin is commented out from wmr, all sourcemaps start working

**Comment by marvinhagemeister** [comment]
Had a go at this over the weekend and there are various places which are not aware of sourcemaps yet. Those generate wrong line and column mappings or miss source information completely. The `default-laoders` plugin is one of those places. Then the other question is about how to merge all the maps from the generated stages. This part is a little trickier and something other tools seem to have trouble with too.

One reason for column mismatches seems to be that something in our stack interprets column mappings wrong when a new line begins. The spec clearly says that _all_ column positions of the original file are relative to the previous one, but something resets it to `0` with each new line.

Also found various ways to speed up source map generation and parsing in itself by eliminating all cases of allocations. The underlying library of `magic-string` that does the soucemapping puts a lot of pressure on the GC.

Looking forward to dive deeper into this!

**Comment by Inviz** [comment]
Sounds super exciting!
