### ISSUE TITLE
TypeError with shorthand JSX Fragments

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/wmr#70]
The following code leads to a `TypeError`:

```jsx
<>foo</>
```

Message (only displayed in browser console):

```
Uncaught (in promise) TypeError: error loading dynamically imported module
```

**Comment by fabiospampinato** [comment]
Fragments still thrown for me, I'm getting the following:

```
layout.tsx:14 Uncaught ReferenceError: $$html is not defined
```

Which disappears if I use a plain `<div>` instead.

I have this in tsconfig.json:

```
    "jsx": "preserve",
    "jsxFactory": "preact.h",
    "jsxFragmentFactory": "preact.Fragment",
```

And this in package.json:

```
  "alias": {
    "react": "preact/compat",
    "react-dom": "preact/compat"
  },
```

Am I missing something? 🤔

**Comment by fabiospampinato** [comment]
Somewhat interesting if I use the ugly Fragment component imported like this:

```
import {Fragment} from 'preact';
```

It works.

But if I import it from 'react' it says:

```
Uncaught SyntaxError: The requested module '/@npm/react' does not provide an export named 'Fragment'
```

So I guess there's also a problem with the rewrite.

**Comment by fabiospampinato** [comment]
Adding aliases for preact in wmr.config.mjs fixes the import issue. I guess those aliases override the one defined in package.json then?

**Comment by marvinhagemeister** [comment]
> Adding aliases for preact in wmr.config.mjs fixes the import issue. I guess those aliases override the one defined in package.json then?

Yeah, they do. I can see how this is confusing so made a PR to update the starter template to declare aliases in the config file for consistency. See #741 

> But if I import it from 'react' it says:
>
> ```
> Uncaught SyntaxError: The requested module '/@npm/react' does not provide an export named 'Fragment'
> ```
>
> So I guess there's (also?) a problem with the rewrite.

The `react` package doesn't have a native ES-Modules entry. It's only shipped as in CommonJS format which needs to be transpiled first to be usable in the browser. Better interop with older module formats is on the todo list. It works flawlessly with Preact because that library ships with native ES-Modules entries and therefore supports modern environments out of the box.

> Fragments still thrown for me, I'm getting the following:
> 
> ```
> layout.tsx:14 Uncaught ReferenceError: $$html is not defined
> ```

I'm very curious to see what code snippet causes it. Would love to fix that! I can't reproduce that on my end.

**Comment by fabiospampinato** [comment]
> I'm very curious to see what code snippet causes it. Would love to fix that. I can't reproduce that on my end.

I'll try to make a repro 👍
