### ISSUE TITLE
WMR does not support .mdx or .md files

### ISSUE THREAD

**Issue by rschristian** [preactjs/wmr#721]
## **Describe the bug**
`.mdx` as well as `.md` files are not being passed to a plugin specifically added in order to handle those file types. As a result, the user gets errors in their browser upon serving those files that have not been processed. 

## **To Reproduce**
```
yarn create wmr xdm-example
yarn add xdm --dev
```

Add an import to `public/index.js`
```js
import Content from './content.mdx';
```

Create `public/content.mdx`
```bash
echo "# Hello World" > public/content.mdx
```

Add XDM Rollup plugin
```js
import xdm from 'xdm/rollup.js';`

export default function (config) {
    config.plugins.push(xdm());
}
```

Navigate to `node_modules/xdm/lib/integrations/rollup.js` and add at line 32:
```js
console.log('xdm:', path);
```

Then start the dev server. Notice in the logs:
```
xdm: ./style.css
xdm: ./index.js
xdm: ./pages/home/index.js
xdm: ./pages/_404.js
xdm: ./header.js
```

No mention of `content.mdx`, and the browser should print the following error into the console:

```
Loading module from “http://localhost:3000/example.mdx” was blocked because of a disallowed MIME type (“text/mdx”).
```

## **Expected behavior**
MDX files (along with other file types as well) should be passed to plugins that might be used in order to handle those file types.

**Desktop (please complete the following information):**

- Node Version: 14.16.0
- WMR Version: 3.2.0

## **Additional context**
I'll certainly look into it, but there's areas of WMR that I still haven't even glanced at, so not sure how far I'll get.

**Comment by marvinhagemeister** [comment]
That's something I'd like to change in general about the plugin system. Currently it only receives specific files, but we should pass any file through it. This would allow plugins hooking into `.html` files too.

**Comment by marvinhagemeister** [comment]
This is the line that's preventing that:

https://github.com/preactjs/wmr/blob/33a046b29f8de85b6e19a33b1b086c37f91e5dc8/packages/wmr/src/wmr-middleware.js#L287
