### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by juanluispaz** [preactjs/wmr#726]
**Is your feature request related to a problem? Please describe.**
preact-iso is awesome. I just miss one basic functionality: Internationalization

**Describe the solution you'd like**
An integral i18n solution for use in Preact that support text translations and plurals. That extract the texts to po and json format.

**Describe alternatives you've considered**
[LinguiJS](https://lingui.js.org) is a lightweight solution than can be integrated into WMR (maybe as an official plugin). Or maybe take some inspirations from it.  

**Additional context**
wmr and preact-iso offers most of the basic functionality required to start building a Preact project; i18n is the biggest absent.

**Comment by developit** [comment]
Hi @juanluispaz! FWIW I just took a look at Lingui's React bindings, and they should work fine with Preact. If you're wanting to avoid `preact/compat` you can alias `"react"` to a module that exports this:

```js
import * as preact from 'preact';
import * as hooks from 'preact/hooks';
export default { ...preact, ...hooks };
```

**Comment by juanluispaz** [comment]
@developit LinguiJS relies on some Babel macros, and I'm not sure how it works with WRM. Unfortunately, there is no documentation about Babel usage in WRM, additionally and without full knowledge of it, WRM looks like to be trying to avoid Babel in favour of Sucrase.

For me, it is not important if LinguiJS is the way or not. The only requirement that I have is to extract the texts automatically to a po file and read the translations from the corresponding translated file.

I think having out-of-the-box i18n support would be a marvellous addition, making it even easier to use preact in real projects.

**Comment by marvinhagemeister** [comment]
@juanluispaz Sucrase doesn't replace babel in WMR. We only use sucrase for TypesScript compilation. Here is how you can use Babel with WMR:

```js
import { transformSync } from "@babel/core";

function MyBabelPlugin() {
  return {
    name: "my-babel-plugin",
    transform(code, id) {
      const result = transformSync(
        code,
        { plugins: [...], presets: [...] }
      );
      
      return { code: result.code, map: result.map }
    }
  }
}
```

> LinguiJS is a lightweight solution than can be integrated into WMR (maybe as an official plugin). Or maybe take some inspirations from it.

I'm worried about taking on additional maintenance of a third-party library right now. What's speaking against having this as a user plugin? Plugins can be freely distributed and shared on npm for everyone to use.

> I think having out-of-the-box i18n support would be a marvellous addition, making it even easier to use preact in real projects.

It's a balancing act for sure as there are many different valid ways to do i18n. Some prefer library A, others B and some prefer something completely different. A popular one right now seems to be `react-i18next` (can be used with Preact through `preact/compat`). I guess the thing is that most i18n solutions can be used in any framework. Even `react-18next` is just a very thin wrapper around `i18next`. In one project I've just used `i18next` directly.

Right now the WMR is pretty much framework independent, except for a few places which will be moved to a `preact` preset soon. WMR is currently positioned as a generic bundler and not as a full encompassing kitchen-sink framework like nextjs.

It's an interesting thought and a question we should ask ourselves if we want to move in that direction.

**Comment by developit** [comment]
While it's on my mind, I was thinking: extracting translations to PO files seems like something that can be done separately from building an application - I seem to recall some solutions split this out as it's own concern (maybe react-intl?).

If I end up spending time noodling on this and find a solution that works, it feels like a demo would be the right avenue (rather than something built into WMR or preact-iso). Internationalization is tricky to get right, and there are a number of different solutions that all have solid tradeoffs worth comparing - I wouldn't want to push folks in a single direction.

**Comment by marvinhagemeister** [comment]
Closing as there are no further tasks for us.
