### ISSUE TITLE
Error when loading SCSS file

### ISSUE THREAD

**Issue by fabiospampinato** [preactjs/wmr#745]
**Describe the bug**

I can't get SCSS files to load at all, I thought this was just unsupported but according to some issues here it seems like that's supposed to be working?

**To Reproduce**

I don't have a minimal repro to share, but basically I'm just adding this to my index.html:

```html
<link rel="stylesheet" href="/public/static/scss/index.scss" />
```

And when reloading the page I'm getting the following error in the console:

```
500 ./src/public/static/scss/index.scss - The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

  at open (internal/fs/promises.js:306:10)
  at Object.readFile (internal/fs/promises.js:618:20)
  at Object.transform (/Users/fabio/Desktop/root-wmr/node_modules/wmr/wmr.cjs:2:1167858)
  at async Object.transform (/Users/fabio/Desktop/root-wmr/node_modules/wmr/wmr.cjs:2:2847140)
  at async js (/Users/fabio/Desktop/root-wmr/node_modules/wmr/wmr.cjs:2:2886396)
  at async Array.<anonymous> (/Users/fabio/Desktop/root-wmr/node_modules/wmr/wmr.cjs:2:2884103)
```

Same if I import it as an ESM module.

If I use a bogus url instead I get the following:

```
404 ./src/public/static/scss/index123.scss - File not found

  at  (:-1:-1)
```

So it seems like it is trying to do something but failing to.

**Expected behavior**

It should just work.

**Desktop (please complete the following information):**

- OS: macOS 10.14
- Browser: Chrome 91
- Node Version: 14.11.0
- WMR Version: 3.3.1

**Additional context**

N/A.

**Comment by developit** [comment]
@fabiosantoscode what does your `index.scss` look like? Are there any imports in it?

**Comment by Inviz** [comment]
https://github.com/preactjs/wmr/issues/731 similar issue i had. only when imported from html

**Comment by marvinhagemeister** [comment]
What does the file structure look like? The `public` part in `./src/public/static/scss/index123.scss` specifically is looking strange to me.

**Comment by fabiospampinato** [comment]
> @fabiosantoscode what does your index.scss look like? Are there any imports in it?

It has some imports in theory, but I'm getting an identical error if I replace the content of that file with the following:

```scss
html {
  background: red;
}
```

**Comment by fabiospampinato** [comment]
> What does the file structure look like of your project? The public part in ./src/public/static/scss/index123.scss specifically is looking strange to me. Knowing that would help tremendously in tracking this down and creating a fix.

Currently my filesystem structure looks like this:

```
- app
  - src
    - public
      - static
        - scss
          - index.scss
    - index.tsx  
    - index.html
```

And I'm starting WMR from `app` with `npx wmr start --public src`.

It's kind of weird structure, it's not the one that I want actually, just trying to figure that out too https://github.com/preactjs/wmr/issues/746

**Comment by fabiospampinato** [comment]
> #731 similar issue i had. only when imported from html

It looks similar yeah, but you mentioned that importing it from JS works, while importing it as `import 'path/to/file.scss'` gives me the same error.

**Comment by developit** [comment]
My guess is that addressing #746 will fix this in your project. Seems like we could have a friendlier error message for missing sass files though?  It's possible there is an error happening [here](https://github.com/preactjs/wmr/blob/a39003cd452fdd00c201ed7af3e94166605b69b4/packages/wmr/src/plugins/sass-plugin.js#L114), but the error text is being masked by a second error in the `catch()` clause when we try to [read the file for sourcemaps](https://github.com/preactjs/wmr/blob/a39003cd452fdd00c201ed7af3e94166605b69b4/packages/wmr/src/plugins/sass-plugin.js#L139).

**Comment by fabiospampinato** [comment]
> Seems like we could have a friendlier error message for missing sass files though?

Is it missing though? If I actually point to a missing file (`index123.scss`) it simply tells me "File not found", for the existing file I'm getting a different error.

**Comment by marvinhagemeister** [comment]
I tried to reproduce the described issue, but I'm unable to. The `scss` file is loaded as expected for me. See https://github.com/marvinhagemeister/wmr-src-rewrite-demo

**Comment by fabiospampinato** [comment]
@marvinhagemeister Interestingly I can't reproduce it with your repro either, but, the issue seems to be that I need to install `sass` for this to work! My bad, I thought a sass compiler was bundled into WMR itself. 

Maybe it could be worth bundling `sass`?

Otherwise I think it'd be useful to mention this detail somewhere in the docs, especially considering that there's some confusion given that there's both node-sass and sass available on NPM, probably WMR only works for `sass`? Even just having a clearer error message for when sass needs to be installed would do wonders.

As a side note: I don't know if I have broken NPM somehow, but for whatever reason on my system running `npm i sass` installs `node-sass`, not `sass` 🤷‍♂️ If this quirk comes from NPM itself I think that's another compelling reason for shipping WMR with `sass` and make this super smooth.

**Comment by rschristian** [comment]
[`node-sass`  has been deprecated for over 9 months now](https://github.com/sass/node-sass/commit/e2391c259167a9692f2c23b0c91caa37502334ca), with issues extending long before then.

Definitely want to move away from using it if you still are.

**Comment by marvinhagemeister** [comment]
Both `node-sass` or `sass` will work with WMR. It's very unlikely that we'll bundle direct one of those compilers as it's not as often used as let's say TS. Bundling sass would also double the download size as it's roughly as big as all of WMR. Allowing users to install it on a need-by-need basis works around that.

I'll reopen this issue, because we should definitely do a better job of communicating that no `sass` compiler can be found.
