### ISSUE TITLE
Add support for base64 imports

### ISSUE THREAD

**Issue by fabiospampinato** [preactjs/wmr#749]
**Describe the bug**

I'm trying to build a fairly empty project, but without success.

If I delete the script tag containing a base64-encoded script I get the following error:

```
Generated an empty chunk: "index"

Wrote 167b to disk:
  dist/index.html 167b
  dist/index.553e494c.js 0.00b

TypeError: h is not a function

    at q$e ([worker eval]:1:1665)
```

If I keep that script tag then it just hangs forever.

**To Reproduce**

1. Unpack this: [asd.zip](https://github.com/preactjs/wmr/files/6786645/asd.zip) into ~/Desktop/asd
2. Go to ~/Desktop
3. Run `wmr build --public asd --prerender` (assuming wmr is installed globally)

**Expected behavior**

No errors, quick output.

**Desktop (please complete the following information):**

- OS: macOS 10.14
- Node Version: 14.11.0
- WMR Version: 3.3.1

**Additional context**

N/A

**Comment by fabiospampinato** [comment]
It might be useful to mention that base64-encoding stuff is useful for performance at times, so this really shouldn't be causing any issues.

Also I tried that as a workaround against the other issues I'm experiencing with WMR, unfortunately that doesn't seem to be working on my system either.

**Comment by fabiospampinato** [comment]
Different error that I'm getting for doing the same thing on a different codebase:

```
Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths and do not contain invalid characters, received "data:text/css;base64,77u/QGtleWZyYW1lcyByaXBwbGV7MCV7b3BhY2l0eTowO3RyYW5zZm9ybTpzY2FsZSgwKX04JX
```

**Comment by developit** [comment]
Ah - I think we're failing to skip Data URLs somewhere.

FWIW even with that fixed, the build command will fail (and should fail). Passing `--prerender` makes WMR import the first script tag and invoke a `prerender()` function that it must export, and in this example project that module is empty.  We should definitely show a nicer error message when the export is missing though, especially since it's minified.

**Comment by developit** [comment]
Alrighty, I opened 2 PRs for the 2 issues here. Thanks for the repro!

**Comment by fabiospampinato** [comment]
> Passing --prerender makes WMR import the first script tag and invoke a prerender() function that it must export, and in this example project that module is empty.

I see, thanks for the clarification!
