### ISSUE TITLE
Some static assets are not treated as such

### ISSUE THREAD

**Issue by fabiospampinato** [preactjs/wmr#750]
**Describe the bug**

IMO everything that is static should be just served as a static file, meaning probably *.html files should be processed, and everything else should be just served.

Currently only _some_ static files are being treated as such. Maybe WMR is unnecessarily whitelisting some extensions and not others, I'm not sure.

**To Reproduce**

1. Unpack this: [asd.zip](https://github.com/preactjs/wmr/files/6786720/asd.zip) to ~/Desktop/asd
2. Go to ~/Desktop
3. Run `wmr start --public asd`
4. See how fetching `/icon.png` works, but for whatever reason querying `/audio.mp3` or `/extensionless` makes WMR think we want a page rather than a file.

**Expected behavior**

I'd expect non *.html files to be served as files.

**Desktop (please complete the following information):**

- OS: macOS 10.14
- Node Version: 14.11.0
- WMR Version: 3.3.1

**Additional context**

N/A

**Comment by developit** [comment]
Hmm - file extensions don't dictate content type:

```
public/
    audio.mp3/
        index.html
```

The above should return an HTML document for `GET /audio.mp3`.

That being said, IIRC we recently added some code that processes HTML files before serving, and my guess is that its inadvertently running on other file types. We should be able to do sniffing to fix this.

**Comment by developit** [comment]
Also one thing to consider: there's quite a difference between requesting a URL by navigating to it in a browser (via the address bar), and requesting a URL by fetch/img/etc.  When you load a URL via the address bar, the browser is sending `Accept: text/html; ...` and that indicates it's looking for an HTML page (if the server can provide one). When you request something via `<audio src="/audio.mp3">` the browser sends `Accept: audio/mp3; audio/*; ...`. When you request via `fetch('/extensionless')` it'll send something like `Accept: */*`.  All of these are treated differently by different servers.

**Comment by fabiospampinato** [comment]
> Hmm - file extensions don't dictate content type:

> there's quite a difference between requesting a URL by navigating to it in a browser (via the address bar), and requesting a URL by fetch/img/etc.

Good points. 

If somebody names a _folder_ foo.mp3 that can be detected and there are no ambiguities there, if somebody queries /foo.mp3 with `Accept: */*`, and a match for that path is found on disk, and that file is a binary file I think that should also be treated unambiguously as a non html page, but more in general I think a much better default would be to process .htm/.html textual files found on disk and just serve the rest, if somebody just uses .mp3 for their html content they are already asking for trouble, I don't think it's a problem if that scenario ~breaks.

**Comment by mate-h** [comment]
My solution for this was to upload the files to Google Cloud Storage and replace the urls. However, tools like https://www.snowpack.dev/reference/configuration#mount allows for configuring which folder to "mount".
```js
// snowpack.config.mjs
// Example: expanded object notation "mount" usage
export default {
  mount: {
    // Same behavior as the "src" example above:
    src: {url: '/dist'},
    // Mount "public" to the root URL path ("/*") and serve files with zero transformations:
    public: {url: '/', static: true, resolve: false},
  },
};
```
Docs:
### Mount local directories to custom URLs in your built application.

* `mount.url` | `string` | __required__: The URL to mount to, matching the string in the simple form above.
* `mount.static` | `boolean` | __optional__ | *Default*: `false`: If `true`, don't build files in this directory. Copy and serve them directly from disk to the browser.
* `mount.resolve` | `boolean` | __optional__ | *Default*: `true`: If `false`, don't resolve JS & CSS imports in your JS, CSS, and HTML files. Instead send every import to the browser, as written.
* `mount.dot` | `boolean` | __optional__ | *Default*: `false`: If `true`, include dotfiles (ex: `.htaccess`) in the final build.

**Comment by marvinhagemeister** [comment]
> I think a much better default would be to process .htm/.html textual files found on disk and just serve the rest

Agree on that. We should just serve the files as is if the url matches a file on disk exactly. The only restrictions I'd add is to ignore dotfiles and only allow matching files when those are in the root directory (default: `public/`). Imo that fits well in line with the spirit of WMR of being a super-powered web server without having to learn new abstractions.

**Comment by zgoda** [comment]
I just discovered this with woff and woff2 font files - woff loads while woff2 does not.
