### ISSUE TITLE
Support for forcing bundled resources to be inlined

### ISSUE THREAD

**Issue by fabiospampinato** [preactjs/wmr#755]
**Is your feature request related to a problem? Please describe.**

I'm making a tiny website, so tiny that I want to ship everything inlined in the html file, but that doesn't currently seem possible.

**Describe the solution you'd like**

Not sure, maybe there could be a configuration option for forcing linked resources to be inlined.

**Describe alternatives you've considered**

Manually performing the inlining like a savage?

**Additional context**

N/A.

**Comment by fabiospampinato** [comment]
A little bit of post-processing seems to do the trick, that's good enough for my use case.

**Comment by developit** [comment]
yep - I believe there's a module called `inline-source` or `inline-source-cli` that does this - nice to have it as its own tool.

**Comment by fabiospampinato** [comment]
That sounds exactly like what I should use, thanks for the suggestion.
