### ISSUE TITLE
Support for users that have javascript disabled

### ISSUE THREAD

**Issue by fabiospampinato** [preactjs/wmr#756]
**Is your feature request related to a problem? Please describe.**

I'm making a little website that doesn't actually require any javascript on the client, but it seems that given how WMR bundles things maybe it's not yet possible to pre-render everything to HTML.

**Describe the solution you'd like**

Maybe that's already possible by providing a `prerender` function that's different from the one provided in the default template?

**Describe alternatives you've considered**

N/A.

**Additional context**

N/A.

**Comment by fabiospampinato** [comment]
Something like this seems to do the job for me:

```ts
import render from 'preact-render-to-string';
import {Homepage} from './pages';

const prerender = () => {
  const html = render ( <Homepage /> );
  return {html};
};
```

**Comment by rschristian** [comment]
You could also just write a simple post-build script to remove any script tags from the built HTML. `preact-iso`'s prerendering has a fair few advantages over this.
