### ISSUE TITLE
"File not found: undefined" on a brand new project

### ISSUE THREAD

**Issue by peterbe** [preactjs/wmr#800]
**Describe the bug**
Can't go to <http://localhost:8080> after having `npm start`. 

<img width="1143" alt="Screen Shot 2021-08-25 at 11 04 39 AM" src="https://user-images.githubusercontent.com/26739/130816090-a21f4dde-82a4-45d1-ac2c-a812a8bf3638.png">

**To Reproduce**

1. `cd /tmp`
2. `npm init wmr repro-overlay-bug`
3. ` cd repro-overlay-bug`
4. `npm start`
5. `open http://localhost:8080`

Note that I haven't touched any files at all. Just run `npm init` and `npm start`. 

**Expected behavior**
I can actually see the sample Home page that is built for a split second but then it goes away. 
Running `npm run build` and `PORT=8080 npm run serve` followed by going to <http://localhost:8080> works fine. 

**Bug occurs with:**

- [x] `wmr` or `wmr start` (development)
- [ ] `wmr build` (production)
- [ ] `wmr serve`

**Desktop (please complete the following information):**

- OS: macOS 11.5
- Browser: latest chrome and firefox
- Node Version: v16.3.0
- WMR Version: 3.5.1

**Additional context**

We really should have a GitHub Action that tests `npm start` and going to the sample app in debug mode. It would have caught this bug.

**Comment by marvinhagemeister** [comment]
Just checked on my linux box and there it works fine. Maybe it's an OS dependent thing?

**Comment by rschristian** [comment]
Or an existing attached service worker perhaps?

**Comment by marvinhagemeister** [comment]
Fixed with #802 . We'll cut a new release for wmr soon.
