### ISSUE TITLE
Overview: Porting preactjs.com to WMR

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/wmr#809]
Today I've attempted to port https://preactjs.com over from `preact-cli` to `wmr`. These are the issues I ran into:

- [x] Missing support for `.less` stylesheets #806 
- [x] Reliance on implicit resolution of `.json` files - _I think we should just rename the few imports in preact-www_ https://github.com/preactjs/preact-www/pull/791
- [x] `.less` files need to be renamed to `.module.less` - _We should just rename them in preact-www_ https://github.com/preactjs/preact-www/pull/791
- [x] Less files use `~` for aliasing, but WMR expects `~/` - _Not sure how much work would be needed to support that in WMR, we could just use standard path imports instead_
- [x] Replace `async!` webpack loaders with `preact-iso` - _There is only one place where it's used explicitely, need to add back code-splitting of pages later though_
- [x] `json:` prefixes don't work with aliased paths - _I'd love to drop the prefixes all together and replace them with `?module`_ https://github.com/preactjs/wmr/pull/810
- [x] Fix npm plugin intercepting relative `.less` imports during production builds `npm registry lookup failed for "mixins.less"`
- [x] Print which file triggered this warning: `Warning: ICSS ("composes:") is only supported in CSS Modules`, otherwise it's a guessing game
- [x] Running into wrong AST transforms - https://github.com/preactjs/wmr/pull/823
- [x] Replace `workerize-loader!` webpack loaders with something else
  - [x] Add support for `this.emitFile({ id: "src/foo.js", type: "chunk" })`, required for https://github.com/surma/rollup-plugin-off-main-thread - WMR now has built-in support for web workers
- [x] Make https://github.com/developit/unistore ESM compatible or use something else? - _Dropped it, because it mostly held routing state and with the switch to `preact-iso` that isn't needed anymore_
- [x] Integrate netlify functions with our dev server middleware

**Comment by developit** [comment]
IIRC, `~` is a prefix in Less that indicates "use the host to resolve this import". My guess is that, in WMR, we could just strip that prefix unconditionally when processing less?

**Comment by developit** [comment]
I threw together a quick implementation of the `async!` prefix as a WMR plugin here:
https://github.com/developit/babel-preset-modernize/blob/website/website/plugins/async-prefix.js

**Comment by developit** [comment]
Not sure which AST transforms you're running into, but if it's when processing things like `babel-standalone` or Codemirror, that was breaking in Webpack and Rollup too - IIRC preact-www is using Webpack's `module.noParse` feature to bypass this (also because it took forever to bundle). If that's what it is, I have a noParse plugin here:
https://github.com/developit/babel-preset-modernize/blob/website/website/plugins/noparse.js

**Comment by developit** [comment]
For the Worker stuff, Comlink feels like it'd be a better option here. Bundling can be done by adding this config:

```js
import OMT from '@surma/rollup-plugin-off-main-thread';

export default function({ mode, plugins }) {
  if (mode === 'build') {
    let omt = OMT({ silenceESMWorkerWarning: true });
    omt.outputOptions({ format: 'esm' });  // this plugin method does validation that breaks in Rollup 2+
    delete omt.outputOptions;  // ... so we spoof it and delete the method (since it was just for validation)
    omt.enforce = 'pre';
    plugins.push(omt);
  }
};

```

**Comment by marvinhagemeister** [comment]
> Not sure which AST transforms you're running into, but if it's when processing things like `babel-standalone` or Codemirror, that was breaking in Webpack and Rollup too - IIRC preact-www is using Webpack's `module.noParse` feature to bypass this (also because it took forever to bundle). If that's what it is, I have a noParse plugin here:
> [https://github.com/developit/babel-preset-modernize/blob/website/website/plugins/noparse.js](https://github.com/developit/babel-preset-modernize/blob/website/website/plugins/noparse.js?rgh-link-date=2021-08-29T16%3A51%3A39Z)

It looks like the double transform issue we've been observing for a while. It happens with the markdown parser:

```js
function applyEmoji(content) {
	if (!content.match(/([^\\]):[a-z0-9_]+:/gi)) {
		return Promise.resolve(content);
	}

	if (processEmojis) {
		return Promise.resolve(processEmojis(content));
	}

	if (!pendingEmojiProcessor) {
	    // BAD replacement
		pendingEmojiProcessor = import(
/@alias/~/lib/gh-emoji/index.js'./gh-emoji'
		).then(({ replace }) => (processEmojis = replace || String));
	}
	return pendingEmojiProcessor.then(processEmojis => processEmojis(content));
}
```

**Comment by marvinhagemeister** [comment]
Turns out the wrong AST was caused by an offset issue in our import specifier logic. See https://github.com/preactjs/wmr/pull/823

**Comment by marvinhagemeister** [comment]
With WMR 3.7.0 all those issues are no fixed 🎉
