### ISSUE TITLE
`onLoadEnd` fires on every render on `preact-iso`'s Router

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/wmr#836]
**Describe the bug**
`onLoadEnd` is fired on every render instead of only once when the promise is resolved.

**To Reproduce**

1. Render from a child under the router and update parent state above the router

**Expected behavior**
Only call `onLoadEnd` once the promise is flushed.

**Bug occurs with:**

- [x] `wmr` or `wmr start` (development)
- [x] `wmr build` (production)
- [ ] `wmr serve`

**Comment by developit** [comment]
ahhh interesting - there are cases where routes don't suspend at all and `onLoadEnd` needs to get called (even though onLoadStart isn't called), but a state update that doesn't modify the route seems like it shouldn't re-invoke routing at all. Good catch.

**Comment by marvinhagemeister** [comment]
Maybe we can just track if `onLoadEnd` was called before and skip calling that if it hasn't been invalidated by another `onLoadStart`
