### ISSUE TITLE
Minify option is ignored for build mode

### ISSUE THREAD

**Issue by andrewiggins** [preactjs/wmr#841]
**Describe the bug**
I have a use case where I'd like to disable minification on build: I'm deploying a test playground I want to be able to nicely debug in the browser. It's not production but I'd like to deploy it

**To Reproduce**

1. Run `wmr build --minify false`
2. Notice that build output is minified

**Expected behavior**
I expect build output to not be minified

**Bug occurs with:**

- [x] `wmr` or `wmr start` (development)
- [x] `wmr build` (production)
- [x] `wmr serve`

**Desktop (please complete the following information):**

- OS: Window 10
- Node Version: 14.17.4
- WMR Version: 3.6.1

**Additional context**
I looked into but didn't have time to open a PR.

It appears cli.js is doing some options normalization ([1](https://github.com/preactjs/wmr/blob/601e46792529cfcfda3ff03295a1d9a687ee6d30/packages/wmr/src/cli.js#L34), [2](https://github.com/preactjs/wmr/blob/601e46792529cfcfda3ff03295a1d9a687ee6d30/packages/wmr/src/cli.js#L15), [3](https://github.com/preactjs/wmr/blob/601e46792529cfcfda3ff03295a1d9a687ee6d30/packages/wmr/src/cli.js#L60)) that should probably move to normalizeOptions.js. I think that's fix the issue.

**Comment by developit** [comment]
@andrewiggins I thought the option was `--no-compress`?

**Comment by marvinhagemeister** [comment]
@developit `--no-compress` is microbundle. Here in wmr the `--compress` is used to toggle gzip compression for the webserver

**Comment by developit** [comment]
Ah right.
