### ISSUE TITLE
Styles from Css modules not being applied in dev mode on windows

### ISSUE THREAD

**Issue by RodrigoJuliano** [preactjs/wmr#871]
**Describe the bug**
Styles using class selector in css modules are not applied. Non module css works fine. No console or terminal errors.
Running from wsl all works fine.

**To Reproduce**

1. Run the demo `yarn demo start`
2. Open the page in a browser
3. See that the background color and font color are not applied to home section

**Expected behavior**
All styles from css modules must be applied

**Bug occurs with:**

- [x] `wmr` or `wmr start` (development)
- [ ] `wmr build` (production)
- [ ] `wmr serve`

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: chrome, edge
- Node Version: v14.17.6 (lts)
- WMR Version: 3.7.1

**Additional context**

**Comment by JoviDeCroock** [comment]
I've just tried doing this by creating a file named `style.module.css` with content:

```css
.abc {
	background-color: blue;
}
```

And applied it to the div of the demo and it all seemed to work well on Windows 10 Node 14 chrome

**Comment by RodrigoJuliano** [comment]
The css is not being transformed
Running on windows:
![image](https://user-images.githubusercontent.com/30511004/133920374-fb4cdc9b-c50c-47ea-9885-c65b7a8db594.png)

Running on wsl:
![image](https://user-images.githubusercontent.com/30511004/133920362-e9045961-e9b8-4e2c-86e6-6ad4357f2e78.png)

**Comment by RodrigoJuliano** [comment]
I found that css files in the root are transformed but in subfolders they are not. Can you confirm? Maybe it's a problem with path conversion.
