### ISSUE TITLE
"404 /@npm/@npm/object-assign - npm registry lookup failed for "@npm/object-assign": Package doesn't exist."

### ISSUE THREAD

**Issue by ruifortes** [preactjs/wmr#882]
Hi.
I'm getting this error message with no apparent cause.
Is this some issue with cdn itself?

I'm using windows 10.

Anything I can do to isolate the problem?

**Comment by mdcanham** [comment]
Hey, I'm struggling with this. I'm not seeing any locked files — do you remember how you resolved this?

**Comment by rejhgadellaa** [comment]
Having the same problem but not just object-assign, I also get it for react-is:

```
/@npm/@npm/react-is - npm registry lookup failed for "@npm/react-is": Package doesn't exist.
```

Everything works fine, and then at some point it doesn't and I get this error ?

**Comment by mdcanham** [comment]
Yeah I'm getting this with `@npm/filter-obj` so a different package too.

`404 /@npm/@npm/filter-obj@1.1.0 - npm registry lookup failed for "@npm/filter-obj": Package doesn't exist.`

**Comment by rejhgadellaa** [comment]
Restarting the vscode window for the project seems to fix it, at least for a while. That would confirm @ruifortes' comment that vscode locks something?

**Comment by rejhgadellaa** [comment]
Just ran int the issue again and while I was trying to get it back to work, I noticed Windows Terminal (Powershell) was complaining that it couldn't delete the node_modules folder without forcing the deletion:

```
node_modules\rgui-preact-core is an NTFS junction point
```

This may be related?

**Comment by rejhgadellaa** [comment]
Since this ticket is closed, I've created a new ticket with additional info: #903
