### ISSUE TITLE
The requested module '/@npm/scheduler' does not provide an export named 'unstable_NormalPriority'

### ISSUE THREAD

**Issue by Aloento** [preactjs/wmr#922]
**Describe the bug**
```
Uncaught SyntaxError: The requested module '/@npm/scheduler' does not provide an export named 'unstable_NormalPriority' (at react-context-selector:3:36)
```

from `import { unstable_NormalPriority as NormalPriority, unstable_runWithPriority as runWithPriority } from 'scheduler';`  
in `\node_modules\@fluentui\react-context-selector\lib\createContext.js`

`unstable_NormalPriority` from `\node_modules\scheduler\cjs\scheduler.{Env}.js`
defined in `\node_modules\@types\scheduler\index.d.ts`

**To Reproduce**
`yarn create wmr & yarn add @fluentui/react-components` 

index.js
```diff
export function App() {
  return (
    <LocationProvider>
+      <FluentProvider theme={webLightTheme}>
        <div class="app">
          <Header />
          <ErrorBoundary>
            <Router>
              <Route path="/" component={Home} />
              <Route path="/about" component={About} />
              <Route default component={NotFound} />
            </Router>
          </ErrorBoundary>
        </div>
+      </FluentProvider>
    </LocationProvider>
  );
}
```

**Comment by rschristian** [comment]
Just want to add to this issue that adding `@rollup/plugin-commonjs` does make the error disappear for me, so it sounds like once we narrow that weird Rollup version bug down you should have a working solution to this.

For any other readers, you can do the following:

```
$ yarn add @rollup/plugin-commonjs
```

> wmr.config.mjs

```diff
 import { defineConfig } from 'wmr';
+import commonjs from '@rollup/plugin-commonjs';

 // Full list of options: https://wmr.dev/docs/configuration
 export default defineConfig({
     /* Your configuration here */
     alias: {
         react: 'preact/compat',
         'react-dom': 'preact/compat'
     },
+    plugins: [commonjs()]
 });
```

**Comment by developit** [comment]
@Aloento there's no need to create a new issue for each broken package - they're all the same issue: WMR doesn't support conditional re-exports in CommonJS modules. This affects all packages published by the React team, and a number of packages from the React community that have copied their packaging design.
