### ISSUE TITLE
preact-iso useLocation missing hash

### ISSUE THREAD

**Issue by dudo** [preactjs/wmr#939]
**Describe the bug**

I'm trying to get the url fragment component out of a callback (anything after a `#`). As it stands, when a `#` is in the url, everything shows as null

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/2963800/193481788-6c17c71c-6bec-4d11-a912-aca7bc5712cf.png">

**To Reproduce**

```js
import { useLocation } from "preact-iso";

const { url, path, query } = useLocation();
```

**Expected behavior**

Should we be exposing a `hash` key from `useLocation`? Is there another way to grab that?

**Comment by developit** [comment]
Hiya! Because preact-iso doesn't do anything with hashes (routing or otherwise), they're left for the browser to handle.

If you want to use the values you can do this:

```js
const authCallbackParams = new URLSearchParams(location.hash.slice(1))

console.log(params.get('access_token');
```

**Comment by dudo** [comment]
Thank you for the clarification. Vanilla it is!
